### ISSUE TITLE
Ensure that enums have immutable numerical values associated with them

### ISSUE THREAD

**Issue by AnashOommen** [googleads/googleads-dotnet-lib#1]
This has more to do with the way Ads Apis manage their enums. But to summarize the problem, let's say a new value got added / removed from an existing enum across API versions. The generated code would look like this:

v1
==

enum MyEnum {
  value1,  //0
  value2,  //1 
  value3   //2
}

v2
==

enum MyEnum {
  value1,  //0
  value3   //1
}

If someone were to depend on the value associated with the enum for serialization purposes, they need to migrate their database values also when moving from v1 to v2.

.NET's recommended approach is to ensure that values are unique, like this:

enum MyEnum {
  value1 = 0,
  value2 = 1,
  value3 = 2
}

However, the code generator doesn't have a good way of ensuring this kind of a numbering, so a possible workaround would be

enum MyEnum {
  value1 = crc32("value1"),
  value2 = crc32("value2"),
  value3 = crc32("value3")
}

This works across versions, but it is not backward compatible.

**Comment by christopherseeley** [comment]
Fixed in 18.31.0
