### ISSUE TITLE
OAuthTokenGenerator.exe is missing in v21.1.0 binary distribution

### ISSUE THREAD

**Issue by nicoara** [googleads/googleads-dotnet-lib#101]
https://github.com/googleads/googleads-dotnet-lib/releases/tag/v21.0.0

**Comment by AnashOommen** [comment]
I see it in both adwords_dotnet_lib_v21.0.0.zip and dfp_dotnet_lib_v21.0.0.zip. Could you provide more details pls?

**Comment by AnashOommen** [comment]
Closing as not replicable.
