### ISSUE TITLE
google adwords revoke refresh token issue

### ISSUE THREAD

**Issue by sachin81094** [googleads/googleads-dotnet-lib#103]
Hey,
I am using asp.net web application to record conversions on google adwords 

account, While revoking the refresh token using  class 

OAuth2ProviderForApplications's method RevokeRefreshToken, It takes sometime 

to revoke the refresh token(5 to 6 seconds) . Can anyone help me how i can use 

this method asynchronously (method will wait untill token is not revoked)

Please update me if anyone having this issue.
Thanks

**Comment by AnashOommen** [comment]
May be you can wrap the call in a Task?

Task task1 = new Task(delegate { 
  oAuthProvider.RevokeRefreshToken();
 });
task1.Start();

var task2 = DoOtherWorkAsync();
await Task.WhenAll(task1, task2);

**Comment by sachin81094** [comment]
@AnashOommen  
Thanks for your reply 
I wrap that code in task as well but still I am facing same issue that I mentioned initially . 

Task revokeTokenTask = new Task(delegate { oAuthProvider.RevokeRefreshToken(); });
revokeTokenTask.Start();
Task removeAccountAccessTask = _integrationService.RemoveAccountAccess(); //this is async method
await Task.WhenAll(revokeTokenTask,removeAccountAccessTask);

I used the above code
Please correct me if I am doing something wrong

Thanks

**Comment by AnashOommen** [comment]
I can no longer replicate this, so I assume this was an issue with the API endpoint and nothing to do with the library per-se. Closing this bug for now, feel free to reopen if the issue persists.
