### ISSUE TITLE
GoogleAdWords to be documented as reserved namespace

### ISSUE THREAD

**Issue by daviburg** [googleads/googleads-dotnet-lib#104]
I made the unfortunate choice to name my solution and project GoogleAdWords prior to add the nuget packages (API and examples). Due to the namespace conflict, the resulting solution can't build. Maybe the documentation should mention to avoid this name for the project and solution.

**Comment by AnashOommen** [comment]
Hi,

You can always change the namespace of your project - https://stackoverflow.com/questions/2871314/change-project-namespace-in-visual-studio.

You can even rename your project - more steps are involved, but it is well-documented too.
https://stackoverflow.com/questions/211241/how-do-i-rename-a-project-folder-from-within-visual-studio

So I am closing this issue assuming my workaround addresses your concerns. If I got this completely wrong, then feel free to reopen this bug, and attach a Visual Studio project that illustrates the issue.
