### ISSUE TITLE
clientCustomerId passed in SOAP header when null, error

### ISSUE THREAD

**Issue by bejan** [googleads/googleads-dotnet-lib#105]
Since the v22 update I get an error when retrieving account information via getCustomers. 

clientCustomerId is not set and not included in the header dictionary that is passed to instantiate the AdWordsUser object, and is commented out at the app.Config. 

The clientCustomerId  value should not be set when retrieving all customers in a managed account. But now in this case the AdWords .NET code transforms properties so that the clientCustomerId is included  in the SOAP header with an empty value. Apparently this causes an error -

AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED @ ; trigger:'<null>'

**Comment by AnashOommen** [comment]
Thanks for pointing this out. We are working on a fix, and this will be live in the next release.

**Comment by christopherseeley** [comment]
Fixed in 22.1.0
