### ISSUE TITLE
PartialFailures broken in v22.1.0?

### ISSUE THREAD

**Issue by Atrejoe** [googleads/googleads-dotnet-lib#107]
After upgrading to [v22.1.0](https://github.com/googleads/googleads-dotnet-lib/releases/tag/v22.1.0) handling of partial failures seems to be broken. At first I thought this was an API issue (see: [Google Groups topic](https://groups.google.com/forum/#!msg/adwords-api/sv3DjwKSm4Y/cT1LG3D0CQAJ;context-place=forum/adwords-api)) 

When only upgrading the library (and not the API version number), the behavior changes, and the partial failures header are no longer honored (so probably the header didn't get sent).

The expected behavior would be when setting request header `partialFailure` to true, the process would not throw an exception upon a single error but return a `partialFailureErrors` array in the return value.

After the update (from 21.1.0) to 22.1.0 an exception is thrown (just when like setting the header to false).

I have used both `v201705` and `v201708` versions of the API.

Unfortunately I didn't get SOAP logging to work, as instructed here: https://github.com/googleads/googleads-dotnet-lib/wiki/How-to-capture-SOAP-messages (I was in the past, so maybe I'm missing something)

**Comment by christopherseeley** [comment]
Thanks for reporting this! This will be fixed in the next release.

**Comment by christopherseeley** [comment]
Fixed in v21.1.1
