### ISSUE TITLE
Access token is no longer refreshed when sending an invalid one

### ISSUE THREAD

**Issue by franckyj** [googleads/googleads-dotnet-lib#109]
Using version 18.33.0 version of the client library and the v201609 API version, when sending an invalid token the `RefreshAccessToken` method of my custom `OAuth2ProviderForApplications` class would get called and refresh the access token automatically.

Now using the latest 22.1.0 version with the v201708 (and even the v201609 API version shows the same behavior) when sending an invalid access token I get the expected `AuthenticationError.OAUTH_TOKEN_INVALID` error from AdWords but my custom `RefreshAccessToken` method is no longer called.

Is there a new configuration that I have to setup in order to bring back that behavior?

**Comment by christopherseeley** [comment]
Does your custom `OAuth2ProviderForApplications` implement `RefreshAccessTokenIfExpiring`? This is called before setting the auth header to prevent invalid auth tokens from being sent.
This avoids the overhead of making a failed call and retrying.

**Comment by franckyj** [comment]
No we don't override that method.

We set both the `UpdatedOn` and the `ExpiresIn` property and we only override the `RefreshAccessToken` method.

In earlier versions I can see with Fiddler that the first call would fail with an OAuth exception. My `RefreshAccessToken` method would get called and the API call would be retried.

What's the distinction between `RefreshAccessTokenIfExpiring` and `RefreshAccessToken`? Should I override both and make them call the same piece of code?

**Comment by christopherseeley** [comment]
`RefreshAccessToken` is not called directly. When getting the Authorization header, this is the code that is called:
https://github.com/googleads/googleads-dotnet-lib/blob/master/src/Common/Lib/OAuth2ProviderBase.cs#L295

It should be calling your `RefreshAccessToken` method if `IsAccessTokenExpiring` returns true. What units are you using for `ExpiresIn` ?

**Comment by franckyj** [comment]
We put a number of of seconds.

But my initial point was that even if the token was "valid" in terms of last access time and duration, if I would to provide an invalid token like the string "invalid token" as the token itself the API call would fail but the AdWords client would sort of know this is a recoverable error and auto-magically call my custom `RefreshAccessToken` method and retry the call.

This behavior was lost somehow between 20.0.0 and 21.0.0. We reverted as far back as 20.0.0 and it worked as before. Updating to 21.0.0 would break one of our test that deals with refreshing the access token.

I see that the `RefreshAccessTokenIfExpiring` method is being called but the context of my test is the the token not expired but invalid.

**Comment by christopherseeley** [comment]
Yes, the automatic retry was removed in v21 since `RefreshAccessTokenIfExpiring` is called before each request. The retry should not have been called under normal circumstances.

Aside from your test is this a scenario that you've encountered? The client library shouldn't be making a request with an expired access token. If the token is invalid for another reason, like the user no longer having access to the account, then the automatic retry wouldn't help.

**Comment by franckyj** [comment]
We have multiple applications that can request new access tokens and this was to make sure that if we have one and we get bumped because some other application requested another one, that we wouldn't fail and the refresh logic would kick in.

Though this is a rare occurrence, maybe that test is no longer valid.

Thanks for taking the time to answer my questions.
