### ISSUE TITLE
Expose `IDisposable` through service interfaces

### ISSUE THREAD

**Issue by franckyj** [googleads/googleads-dotnet-lib#111]
With this new 22.0.0 release of the client [it is stated](https://github.com/googleads/googleads-dotnet-lib/wiki/Upgrading-your-client-library-to-v22.0.0) that all the services now implement the `IDisposable` interface.

This is good but this new feature isn't exposed through the different service interfaces (ICampaignService, IBudgetService, etc.). Our code exposes the interfaces rather than the concrete implementation since it is easier to test by mocking the return values of different `get`s and `mutate`s.

Would it be possible to expose the `IDisposable` interface in the service interfaces?

I understand that it is a bit counter intuitive since interfaces are more about contracts rather then lower level features like how to clean up objects but I think it would be beneficial.

Let me know what you think,
Francois

**Comment by AnashOommen** [comment]
Ack, will try to provide this in an upcoming release.

**Comment by AnashOommen** [comment]
Fixed in v22.3.0.
