### ISSUE TITLE
AdWordsUserListService reference incorrectly creating Jagged Array

### ISSUE THREAD

**Issue by EdGrave** [googleads/googleads-dotnet-lib#112]
When creating a new service reference from the AdWordsUserListService WSDL the Rule class is creating the private _groupsfield_ and public _groups_ field as a jagged array of _RuleItem_ objects.
    private RuleItem[][] groupsField;
    public RuleItem[][] groups 
This is causing the serialisation to fail when an _ExpressionRuleUserList_ is brought in from the _get()_ method.
I have a work around to change the jagged arrays to a regular array but anytime I update the service reference it replaces the fix with the jagged array.
Looking at the WSDL definition it seems like there is a missing _RuleIemGroup_ array in the object structure.

**Comment by AnashOommen** [comment]
Welcome to the world of SOAP stub generation! This behaviour you mentioned is a bug / feature / working as intended depending on who you ask. We have the fixed stubs in our client libraries, and they are same as what svcutil would generate, but with some fixes. 

I recommend using the client library if you can; it if doesn't, let me know why it wouldn't work for you and we will try to find another way out.
