### ISSUE TITLE
Google.Api.Ads.Common.Lib.AdsOAuthException was unhandled by user code - HResult=-2146233088 -Failed to get access token for service account - Client is unauthorized to retrieve access tokens using this method

### ISSUE THREAD

**Issue by jhodges13** [googleads/googleads-dotnet-lib#113]
We have a few .Net projects at my company that use Google.Api.Ads.Dfp.Lib and they apparently stopped working in December 2016 and none of the developers here have been able to fix it. They were built using a P12 file for authentication, I'm told it needs to be redone to work with oAuth2 and a JSON file.

I'm relatively new to the company and was asked to fix this. I have no background on Google DFP (DoubleClick for Publishers) and the original developer no longer works here and left no documentation. I gave up trying to get the original projects working (for now) and have been trying to get the google DFP .Net example code to run against our Production Data. My goal is to connect successfully and get a particular method working GetCreativesByStatement(); then hopefully that will point me to how to fix the main program.

So I've been tinkering at this for a week now. I finally got access to create credentials and setup services accounts. I've got my API Project JSON files loaded into the project. I successfully used the OauthTokenGenerator to create a token. I have the token information copied into the app.config which configured for ServerToServer.

When I debug "Def.Examples.CSharp.v201705" it gives me the error below. I think I have things configured properly but I'm not 100% positive. Couple blogs have suggested this is a permission problem I am experiencing, that I need to enable access to an API somehow but so far I can't find anything.

I'd appreciate any suggestions or help.

Google.Api.Ads.Common.Lib.AdsOAuthException was unhandled by user code - HResult=-2146233088 - 
  HResult=-2146233088
  Message=Failed to get access token for service account.
{
  "error" : "unauthorized_client",
  "error_description" : "Client is unauthorized to retrieve access tokens using this method."
}
  Source=Google.Ads.Common
  StackTrace:
       at Google.Api.Ads.Common.Lib.OAuth2ProviderForServiceAccounts.GenerateAccessTokenForServiceAccount() in C:\Users\dspsvcFarmAcc\Desktop\GoogleSampleCode\googleads-dotnet-lib-master\googleads-dotnet-lib-master\src\Common\Lib\OAuth2ProviderForServiceAccounts.cs:line 136
       at Google.Api.Ads.Common.Lib.OAuth2ProviderForServiceAccounts.RefreshAccessToken() in C:\Users\dspsvcFarmAcc\Desktop\GoogleSampleCode\googleads-dotnet-lib-master\googleads-dotnet-lib-master\src\Common\Lib\OAuth2ProviderForServiceAccounts.cs:line 147
       at Google.Api.Ads.Common.Lib.OAuth2ProviderBase.RefreshAccessTokenIfExpiring() in C:\Users\dspsvcFarmAcc\Desktop\GoogleSampleCode\googleads-dotnet-lib-master\googleads-dotnet-lib-master\src\Common\Lib\OAuth2ProviderBase.cs:line 305
       at Google.Api.Ads.Common.Lib.OAuth2ProviderBase.GetAuthHeader() in C:\Users\dspsvcFarmAcc\Desktop\GoogleSampleCode\googleads-dotnet-lib-master\googleads-dotnet-lib-master\src\Common\Lib\OAuth2ProviderBase.cs:line 296
       at Google.Api.Ads.Common.Lib.OAuth2ClientMessageInspector.BeforeSendRequest(Message& request, IClientChannel channel) in C:\Users\dspsvcFarmAcc\Desktop\GoogleSampleCode\googleads-dotnet-lib-master\googleads-dotnet-lib-master\src\Common\Lib\OAuth2ClientMessageInspector.cs:line 50
       at System.ServiceModel.Dispatcher.ImmutableClientRuntime.BeforeSendRequest(ProxyRpc& rpc)
  InnerException: 

AppConfig DFPApi looks like this:  (I've X'd out anything sensitive)

  <DfpApi>
    
    <add key="MaskCredentials" value="true" />

    

    
    

    
    

    
    <add key="EnableGzipCompression" value="true" />

    
    <add key="IncludeUtilitiesInUserAgent" value="true" />

    
    <add key="ProxyServer" value="" />
    <add key="ProxyUser" value="" />
    <add key="ProxyPassword" value="" />
    <add key="ProxyDomain" value="" />

    
    <add key="ApplicationName" value="XXXXX" />
    <add key="NetworkCode" value="55555555" />

    <add key="OAuth2Mode" value="SERVICE_ACCOUNT"/>
    <add key="OAuth2SecretsJsonPath" value=".\API Project-1c322fb8912b.json"/>
    <add key="OAuth2PrnEmail" value="XXXXXXX" />
    
    
    <add key="AuthorizationMethod" value="OAuth2" />
    <add key="OAuth2ClientId" value="XXXXXXXXXXXXXXXX" />
    <add key="OAuth2ClientSecret" value="XXXXXXXXXXXXXX" />
    <add key="OAuth2RefreshToken" value="XXXXXXXXXXXXXX" />
    
  </DfpApi>

**Comment by jhodges13** [comment]
I figured this out. The app.config needs to have far less info in it. I've X'd out sensitive info but the basic structure below got the example working for me for server to server using a Net windows form.  To get the token information, you will need to compile and run the Oauth Token Generator Project. 

Hope this helps someone.

<DfpApi>

<add key="MaskCredentials" value="true" />

<add key="EnableGzipCompression" value="true" />

<add key="IncludeUtilitiesInUserAgent" value="true" />


<add key="ApplicationName" value="XXXXXXXX" />
<add key="NetworkCode" value="XXXXXXXX" />

<add key="AuthorizationMethod" value="OAuth2" />
<add key="OAuth2ClientId" value="XXXXXX.apps.googleusercontent.com" />
<add key="OAuth2ClientSecret" value="XXXXXXXXXXX" />
<add key="OAuth2RefreshToken" value="XXXXXXXX" />

</DfpApi>

**Comment by AnashOommen** [comment]
Apologies for the delay. Your response is correct - you need to keep one of (Service account settings, Server-to-server settings).
