### ISSUE TITLE
No SoapListenerExtension class in v201708

### ISSUE THREAD

**Issue by ldhorner** [googleads/googleads-dotnet-lib#114]
This class has existed in all previous versions (including v201705) but disappeared with the v201708 release. Is this an oversight or is there an alternative class I should be using?

**Comment by christopherseeley** [comment]
This was removed starting in v22 of the library:
https://github.com/googleads/googleads-dotnet-lib/wiki/Upgrading-your-client-library-to-v22.0.0

We no longer use SOAP extensions for logging. You can still configure your logging settings through the system.diagnostics section of the App.config.

If you need similar behavior to the SOAP extension, you can create a custom [IClientMessageInspector](https://msdn.microsoft.com/en-us/library/system.servicemodel.dispatcher.iclientmessageinspector(v=vs.110).aspx) and apply it to the service instead.
