### ISSUE TITLE
Error while migrating Adwords Api to v201708 (Version 22.1.1)

### ISSUE THREAD

**Issue by maheshnerlekar** [googleads/googleads-dotnet-lib#115]
I am trying to install the latest version of Adwords v201708 using NuGet.. using following command on the NuGet Package Manager Console.

PM> Install-Package Google.AdWords -Version 22.1.1

I am getting an error almost at the end...Did anyone else get an error like this?

Install failed. Rolling back...
Install-Package : Could not install package 'Google.Ads.Common 8.0.0'. You are trying to install this package into a project that targets '.NETFramework,
Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, c
ontact the package author.
At line:1 char:16
+ Install-Package <<<<  Google.AdWords -Version 22.1.1
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 
I tried to do with .net framework v4.5. Still the same error. not sure whats the issue... Please let me know if anyone has seen this issue?

Thanks,
Mahesh

**Comment by VictorFZ** [comment]
Hi! In order to install this version of Google.Adwords your Project must be using .net 4.5.2!

**Comment by christopherseeley** [comment]
Yes, this version required 4.5.2 or later. Feel free to reopen if that didn't resolve the issue.
