### ISSUE TITLE
Exception while calling OfflineConversionFeedService

### ISSUE THREAD

**Issue by naterose** [googleads/googleads-dotnet-lib#117]
I am receiving an error attempting to submit a list of offline conversions to the OfflineConversionFeedService of the .Net api.  The error returned was: 
 
> The value of this argument must fall within the range 0 to 0.
> Parameter name: headerIndex
> Actual value was 0.

Here is the summary log from the mutate attempt:

> AdsClientLibs.SummaryRequestLogs Information: 1 : host=accounts.google.com,url=/o/oauth2/token,User-Agent: SPPC (AwApi-DotNet/22.1.0, Common-Dotnet/8.0.0, .NET CLR/4.0.30319.42000, OAuthApplicationFlow), Content-Type: application/x-www-form-urlencoded, Host: accounts.google.com, TimeStamp: Tue, 26 Sep 2017 16:01:32 GMT, client_id=[my_client_ID]&client_secret=REDACTED&refresh_token=REDACTED&grant_type=refresh_token,Result=Success

I am using v201708 and file version 22.1.0.0 of the Google.Adwords.dll.  

This issue was submitted in the adwords api forum and they directed me here as it appears this is occurring while building the api call but before it is submitted.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/adwords-api/bAGICqfoWPg/Yt_8yG0UAgAJ

Please let  me know if you need any other information regarding this issue.  Thanks!

**Comment by christopherseeley** [comment]
Does this happen in v22.1.1? There were a couple bug fixes in that release including one related to headers.

**Comment by naterose** [comment]
Yes, the same error appears to also be happening with v22.1.1

**Comment by christopherseeley** [comment]
I was able to reproduce when passing an invalid conversionTime string format. The SOAP fault is missing headers in this case, and the library should handle this and throw a more appropriate error.

Can you verify that your date times are in the format described here (with time zones):
https://developers.google.com/adwords/api/docs/appendix/codes-formats#timezone-ids

Let me know if you get the exception even with correct date time formats.

**Comment by AnashOommen** [comment]
Hi,

Did you get the issue resolved? i.e. make a request without getting a fault back?

**Comment by AnashOommen** [comment]
Fixed in v22.3.0.
