### ISSUE TITLE
After October 2 - Can not use the AdWords API any more

### ISSUE THREAD

**Issue by NDB56Algoma** [googleads/googleads-dotnet-lib#118]
As stated here "on October 2, 2017. After this date, all v201609 API requests will begin to fail."
The recommendation is to migrate to newer version.

We use:
Google.AdWords v18.34
Google.Ads.Common v3.18
I've tried to migrate but get error that the .Net 4.5 Framework is not supported by the new version.

We can not upgrade the framework for this project because other dependencies and it is very sensitive project in the production environment. 
So it seems that we are going to stop using the AdWords API.

If someone can help here we'll be happy.

**Comment by christopherseeley** [comment]
Starting in v19.0.0 the minimum .NET Famework version was increased to [4.5.2](https://blogs.msdn.microsoft.com/dotnet/2014/08/07/moving-to-the-net-framework-4-5-2/). You'll need to update in order to use this client library.
