### ISSUE TITLE
runtime exception 

### ISSUE THREAD

**Issue by chickeynana** [googleads/googleads-dotnet-lib#120]
![error](https://user-images.githubusercontent.com/25587270/31323952-c146a242-acd7-11e7-85c7-51a35b1ff402.png)

Please help me fixing this runtime exception for the Download criteria report button

**Comment by AnashOommen** [comment]
Could you try turning on logging, and see what gets logged? 500 error means that there is an error with the request itself, and the server is returning an error.

**Comment by AnashOommen** [comment]
Closing for now, feel free to reopen if you face more issues.
