### ISSUE TITLE
exception for "Download report"

### ISSUE THREAD

**Issue by chickeynana** [googleads/googleads-dotnet-lib#121]
![image](https://user-images.githubusercontent.com/25587270/31574815-a97cec9c-b101-11e7-8b25-39f5f9275f8f.png)
![image](https://user-images.githubusercontent.com/25587270/31574817-b54a726a-b101-11e7-8e6d-9ea6939c4faf.png)

**Comment by AnashOommen** [comment]
Hi,

Try moving to the latest version -- v201710.

**Comment by AnashOommen** [comment]
v22.3.0 has support for AdWords API v201710. v201609 got sunset recently. (http://googleadsdeveloper.blogspot.com/2017/08/adwords-api-v201609-sunset-reminder.html)

You can get v22.3.0 here: https://github.com/googleads/googleads-dotnet-lib/releases/tag/v22.3.0
