### ISSUE TITLE
"Unmarshalling Error" calling getCustomers when using AppDynamics

### ISSUE THREAD

**Issue by philjhale** [googleads/googleads-dotnet-lib#122]
I'm seeing internal server errors when using version 22.3.0 of the SDK to call `AdWordsService.v201710.CustomerService.getCustomers()`. 

Here is the stack trace of the exception:

```
System.ServiceModel.FaultException: Unmarshalling Error: unexpected element (uri:"http://appdynamics.com", local:"singularityheader"). 
   Expected elements are <{https://adwords.google.com/api/adwords/mcm/v201710}ApiExceptionFault>,
   <{https://adwords.google.com/api/adwords/mcm/v201710}RequestHeader>,
   <{https://adwords.google.com/api/adwords/mcm/v201710}ResponseHeader>,
   <{https://adwords.google.com/api/adwords/mcm/v201710}getCustomers>,
   <{https://adwords.google.com/api/adwords/mcm/v201710}getCustomersResponse>,
   <{https://adwords.google.com/api/adwords/mcm/v201710}getServiceLinks>,
   <{https://adwords.google.com/api/adwords/mcm/v201710}getServiceLinksResponse>,
   <{https://adwords.google.com/api/adwords/mcm/v201710}mutate>,
   <{https://adwords.google.com/api/adwords/mcm/v201710}mutateResponse>,
   <{https://adwords.google.com/api/adwords/mcm/v201710}mutateServiceLinks>,
   <{https://adwords.google.com/api/adwords/mcm/v201710}mutateServiceLinksResponse>

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Google.Api.Ads.AdWords.v201710.CustomerServiceInterface.getCustomers(getCustomersRequest request)
   at Google.Api.Ads.AdWords.v201710.CustomerService.Google.Api.Ads.AdWords.v201710.CustomerServiceInterface.getCustomers(getCustomersRequest request)
   at Google.Api.Ads.AdWords.v201710.CustomerService.getCustomers()
```

It turns out that AppDynamics inserts a correlation ID into the SOAP header. This causes the internal server error response. 

Here is an example failing request:

```
POST https://adwords.google.com/api/adwords/mcm/v201710/CustomerService HTTP/1.1

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
<s:Header>
	<Test></Test>
	<RequestHeader xmlns="https://adwords.google.com/api/adwords/mcm/v201710">
		<developerToken>Removed</developerToken>
		<userAgent>ActiveAudience (AwApi-DotNet/22.3.0, Common-Dotnet/8.1.0, .NET CLR/4.0.30319.42000, Logging, OAuthApplicationFlow, gzip)</userAgent>
	</RequestHeader>
</s:Header>
<s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><getCustomers xmlns="https://adwords.google.com/api/adwords/mcm/v201710"/>
</s:Body>
</s:Envelope>
```

The `<Test></Test>` SOAP header is a simulation of the AppDynamics correlation information. Without the extra header, the call is successful. With the extra header, the call fails. The response is:

```
HTTP/1.1 500 Internal Server Error

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body>
  <soap:Fault>
    <faultcode>soap:Server</faultcode>
    <faultstring>Unmarshalling Error: unexpected element (uri:"", local:"Test"). Expected elements are &lt;{https://adwords.google.com/api/adwords/mcm/v201710}ApiExceptionFault&gt;,&lt;{https://adwords.google.com/api/adwords/mcm/v201710}RequestHeader&gt;,&lt;
...
    </faultstring>
  </soap:Fault>
</soap:Body>
</soap:Envelope>
```

It is possible to work around the issue by disabling WCF correlation in AppDynamics. But since any user of the SDK who also uses AppDynamics will have to do this, it's not optimal. Is it possible via configuration or code change for the SDK to ignore unexpected SOAP headers?

**Comment by christopherseeley** [comment]
The unmarshalling error is thrown by the API server here, which can't be changed to ignore unexpected headers.

This client library only adds expected SOAP headers. I'm not sure how it could prevent AppDynamics from adding these headers, but I'm open to suggestions.

**Comment by AnashOommen** [comment]
Can AppDynamics add HTTP headers instead for correlation? Or modify an existing SOAP header that's allowed to have freeform text? (e.g. userAgent header)? I'm not familiar with how much customization AppDynamics allow.

**Comment by philjhale** [comment]
I'm a novice when it comes to AppDyanmics configuration. It seems like you can't use HTTP headers to correlate WCF requests. I'll have to contact support for more info.

**Comment by philjhale** [comment]
I contacted AppDynamics support.

- Q: In AppDynamics is it possible to correlate WCF requests by adding HTTP headers?
- A: Technically it is possible by [disabling](https://docs.appdynamics.com/display/PRO43/App+Agent+Node+Properties#AppAgentNodeProperties-editregisterednodepropertyEditaRegisteredNodeProperty) [enable-soap-header-correlation](https://docs.appdynamics.com/display/PRO43/App+Agent+Node+Properties+Reference#AppAgentNodePropertiesReference-EnableSoapHeaderCorrelationenable-soap-header-correlation) node property.
