### ISSUE TITLE
How to set Proxy programmatically

### ISSUE THREAD

**Issue by kst83** [googleads/googleads-dotnet-lib#129]
I want to use a Proxy Server.
How do you set the property Proxy of DfpAppConfig correctly?
Or can it only be set from App.config?

**Comment by AnashOommen** [comment]
you could do

```
DfpAppConfig config = (DfpAppConfig) user.Config;
config.Proxy = your_proxy;
```

**Comment by kst83** [comment]
How do you define your_proxy?
Is the following correct?
```var your_proxy = new WebProxy("proxy.org", 8080);```

**Comment by AnashOommen** [comment]
yep.
