### ISSUE TITLE
Error in Call Metrics Call Details Report

### ISSUE THREAD

**Issue by srmoneypenny** [googleads/googleads-dotnet-lib#131]
I'm attempting to run the CALL_METRICS_CALL_DETAILS_REPORT, but am receiving the following error:
>System.InvalidOperationException: Could not set the member startTime with value Jan 22, 2018 12:41:56 PM

I am requesting the [**CallStartTime** field](https://developers.google.com/adwords/api/docs/appendix/reports/call-metrics-call-details-report#callstarttime) in the ReportDefinition; this appears to be a _long_ (`public long callStartTime`) in `CallMetricsCallDetailsReportReportRow` class. I obviously can't override the type of this property.

```
 ReportUtilities utilities = new ReportUtilities(user, AdWordsVersion, definition);
 using (ReportResponse response = utilities.GetResponse())
 using (GZipStream gzipStream = new GZipStream(response.Stream, CompressionMode.Decompress))
 using (var report = new AwReport<CallMetricsCallDetailsReportReportRow>(new AwXmlTextReader(gzipStream), reportName))
```

Any suggestions would be appreciated! Stack trace below.
```
at Google.Api.Ads.AdWords.Util.Reports.AwReport`1.<>c.<.ctor>b__21_0(ColumnValuePair colVal, A record)
at Google.Api.Ads.AdWords.Util.Reports.ReportParserUtils.SetColumnValue[A](ColumnValuePair colVal, A record, Action`2 onError)
at Google.Api.Ads.AdWords.Util.Reports.AwReport`1.ParseCurrentRow()
at Google.Api.Ads.AdWords.Util.Reports.AwReport`1.get_Current()
at Google.Api.Ads.AdWords.Util.Reports.AwReport`1.GetRows()
at Google.Api.Ads.AdWords.Util.Reports.AwReport`1.get_Rows()
```

**Comment by AnashOommen** [comment]
Hi,

Could you post your report definition / query? I suspect this could be an issue with how ReportDefinitionService is out of sync with the actual value returned by this column.

You can turn on logging as explained here: https://github.com/googleads/googleads-dotnet-lib/wiki#logging. Make sure you set the `MaskCredentials` setting in App.config to `true`, so all the sensitive fields are removed.

**Comment by AnashOommen** [comment]
As a temporary workaround, you can provide an `OnError` handler on the `AwReport` through the constructor. See the definition here:

https://github.com/googleads/googleads-dotnet-lib/blob/8d666a040a736eea200bbb7804adb95116788174/src/AdWords/Util/Reports/Parser/AwReport.cs#L118

You can see the default implementation on line 137 below, which simply throws an InvalidOperationException. You can adapt this logic something like this (syntax not checked, I don't have access to an IDE right now):

```
using (var report = new AwReport<CallMetricsCallDetailsReportReportRow>(new AwXmlTextReader(gzipStream), reportName), delegate(colVal, record) {
      if (colVal.Name ==  "CallStartTime") {
        // Parse from datetime to long using DateTime class.
      } else {
        throw new InvalidOperationException("Could not set the member "
            + colVal.ColName + " with value " + colVal.Value);
        }
      }
) {
  // Your code goes here.
}
```

**Comment by srmoneypenny** [comment]
Thanks for the helpful response! Your approach worked great (correct syntax below; the callEndTime is also a `long`). It also seems like I could just deserialize to my own object using the correct annotations (`ReportColumn`).

The definition was basically:
```
var definition = new ReportDefinition
{
      reportName = "Daily Call Metrics Report",
      reportType = ReportDefinitionReportType.CALL_METRICS_CALL_DETAILS_REPORT,
      downloadFormat = DownloadFormat.GZIPPED_XML,
      dateRangeType = ReportDefinitionDateRangeType.YESTERDAY,
      selector = new Selector
      {
         fields = new[] {
            "CampaignName",
            "CallStartTime", "CallEndTime", "CallDuration",
            "CallerNationalDesignatedCode"
         },
         predicates = new[] {
            Predicate.In("CampaignName", new[]
            {
                  "CampaignNameA", "CampaignNameB"
            })
         }
      }
};
```
Syntactically correct implementation:
```
using (var report = new AwReport<CallMetricsCallDetailsReportReportRow>(new AwXmlTextReader(gzipStream), reportName,
      delegate(ColumnValuePair colValue, CallMetricsCallDetailsReportReportRow record)
      {
         if (colValue.ColName == "startTime" || colValue.ColName == "endTime")
         {
               record.callStartTime = DateTime.Parse(colValue.Value).Ticks;
         }
         else
         {
               throw new InvalidOperationException("Could not set the member " + colValue.ColName + " with value " + colValue.Value);
         }
      }))
```

**Comment by AnashOommen** [comment]
Yep, using your own class to deserialize to is another way to fix it.

**Comment by AnashOommen** [comment]
Closing this issue, since this is actually an API issue, and that there is a workaround for it.
