### ISSUE TITLE
 Could not find default endpoint element in ServiceModel client config - DFP v201711

### ISSUE THREAD

**Issue by stematique** [googleads/googleads-dotnet-lib#132]
Hi all, 
im trying to upgrade .NET client lib from v201702 to v201711 on  a web .net 4.6 application calling a dll class library referencing DFP api client library.
After changing libs and references i cannot reach anymore the google soap service and no matter what kind of Service i call (company, lineitem, order service etc) i always get the following error during the Service Initialization (for example for company service):

`Could not find default endpoint element that references contract 'Google.Api.Ads.Dfp.v201711.CompanyServiceInterface'  in the ServiceModel client configuration section. This might be because no configuration file was found for your application, or because no endpoint element matching this contract could be found in the client element.`

I read this document in github wiki 'Upgrading your client library to v22.0.0' , so i understand something on the backend has been changed.

The problem appears only when i call api libs from a separate dll class library. If i directly call api libs (for example with the examples project included in the client library packet) everything works ok.

Of course nothing changed in my code nor in the config file, if i just revert back Google.Dfp.dll and Google.Ads.Common.dll back to v201702 all still works fine.

I read over the internet that this behavior can happen with the WCF Service model, they just suggest to add the endpoint configuration both in the main app web.config and in the class library app.config. 
Is that a path i can try? as i've never had the need to manually specify google enpoints in config, how can i do it?

Thanks for your help,
ST

**Comment by christopherseeley** [comment]
How are you instantiating the service? Through DfpUser.GetService?

**Comment by stematique** [comment]
Actualy it throws this exception before using GetService, just here:

`Dim itemsrv As New CompanyService`

PS: That project is in vb but i also have different c# project i will have
to update sooner or later, hope vb or c# doesnt make any difference in this
issue

ty in advance

**Comment by christopherseeley** [comment]
That's likely the issue. You shouldn't instantiate the service yourself - just get it from the DfpUser. This VB example is for AdWords, but the idea is the same:
https://github.com/googleads/googleads-dotnet-lib/blob/master/examples/AdWords/Vb/v201710/BasicOperations/GetCampaigns.vb#L57

You probably also want to put services in a Using block as part of your upgrade, as the example above shows.

**Comment by stematique** [comment]
ty so much, that solved!!
