### ISSUE TITLE
No built-in logging support for .NET Core 2.0

### ISSUE THREAD

**Issue by christopherseeley** [googleads/googleads-dotnet-lib#134]
System.Diagnostics.TraceSource isn't reading settings from App.config files under .NET Core 2.0:
https://github.com/dotnet/corefx/issues/24829

We should update the library to workaround this. For now, users on .NET Core can add their own [`IEndpointBehavior`](https://msdn.microsoft.com/en-us/library/system.servicemodel.description.iendpointbehavior(v=vs.110).aspx) to a service and implement their own logging:

    // Get the CampaignService.
    CampaignService campaignService =
         (CampaignService)user.GetService(AdWordsService.v201708.CampaignService);
    campaignService.Endpoint.EndpointBehaviors.Add(myCustomBehavior);

**Comment by AnashOommen** [comment]
Chris, we should switch to ILogger, that seems to be the new standard. It's fairly straightforward to do, but we need to do a major version bump, I guess.

https://msdn.microsoft.com/en-us/magazine/mt694089.aspx

**Comment by AnashOommen** [comment]
Fixed in v23.6.0. We've added couple of utility methods to allow setting up logging at runtime, instead of the configuration in App.config that System.Configuration doesn't recognize in .NET Core, at runtime.
