### ISSUE TITLE
Oauth project crash while following instructions - step 9

### ISSUE THREAD

**Issue by OladotunO** [googleads/googleads-dotnet-lib#136]
Hi There

The Oauth project crash while i am following the readme instructions - step 9

VS 2017 community, fully updated, Windows 7

Error

[FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.]
   Google.Api.Ads.Common.Lib.AppConfigBase.LoadConfigSection(String sectionName) +0
   Google.Api.Ads.AdWords.Lib.AdWordsAppConfig..ctor() in /usr/local/google/users/cseeley/tmp/tmp.qoFWxNjlRu/moesource/src/AdWords/Lib/AdWordsAppConfig.cs:278
   Google.Api.Ads.AdWords.Lib.AdWordsUser..ctor() in /usr/local/google/users/cseeley/tmp/tmp.qoFWxNjlRu/moesource/src/AdWords/Lib/AdWordsUser.cs:44
   Google.Api.Ads.AdWords.Examples.CSharp.OAuth.Default.Page_Load(Object sender, EventArgs e) in C:\Users\admin\Downloads\adwords_dotnet_lib_v23.0.0\examples\AdWords\csharp\oauth\Default.aspx.cs:43
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +51
   System.Web.UI.Control.OnLoad(EventArgs e) +95
   System.Web.UI.Control.LoadRecursive() +59
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +678

**Comment by AnashOommen** [comment]
Ah, the AdWords.Examples.CSharp.OAuth example isn't still converted to use Nuget references. Will get it fixed in the next push.

For now, could you please remove reference to AdWords and Common, and add Nuget reference to Google.AdWords? That should pull in all the required references.

**Comment by OladotunO** [comment]
Thank Anash, that appears to have worked. I now have a loaded browser with authorize user button and other items.

 I removed Google.Adwords, and Google.Ads.Common and then loaded the Google.Adwords Nuget as per your instructions

Cheers

Ola
