### ISSUE TITLE
Timeouts Without ReportResponse

### ISSUE THREAD

**Issue by fredwilliams1981** [googleads/googleads-dotnet-lib#138]
Everything worked fine all day up until about 3pm today. Then I began getting stuck here

`                    using (ReportResponse reportResponse = reportUtilities.GetResponse())
                    {
                        
                        reportResponse.Save(filePath);
                    }`

I began receiving a timeout error stating that the current timeout is set to 10 minutes and suggesting I increase the timeout value. I've got 10 dimensions included as per the recommended limit in the documentation.

**Comment by AnashOommen** [comment]
Timeouts typically is due to a local network issue. The easiest way to confirm this to try reaching a wsdl url (e.g. https://adwords.google.com/api/adwords/cm/v201710/CampaignService?wsdl) from a local browser. Is a wsdl reachable?
