### ISSUE TITLE
How do I fetch all location codes for a country(in array)  to apply LocationSearchParameter: 

### ISSUE THREAD

**Issue by OladotunO** [googleads/googleads-dotnet-lib#141]
Hi All,
I am trying to restrict a targetting ideas script to a chosen country, my code is below, it seems to be wrongI cant find any documentation to guide me. And i am reluctant to manually create an array of 3300 plus ids

               ` Location unitedkingdom = new Location() ;
                unitedkingdom.id = 2826; // UK
                LocationSearchParameter mylocationParam = new LocationSearchParameter();
                mylocationParam.locations = unitedkingdom.parentLocations ;
                searchParameters.Add(mylocationParam);`

**Comment by AnashOommen** [comment]
Could you pls post on the AdWords API forum? That’s the standard channel for asking API questions.

https://groups.google.com/forum/m/#!forum/adwords-api

Also, the documentation is here: https://developers.google.com/adwords/api/docs/guides/start
