### ISSUE TITLE
Visual Studio 2015 - The default XML namespace of the project must be the MSBuild XML namespace. 

### ISSUE THREAD

**Issue by Saritha535** [googleads/googleads-dotnet-lib#142]
I am trying to add adwords project to my source project in VS2015 then am getting error like this below.

**Visual Studio 2015 - The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add 
xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. if the project has been authored  in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 fromat.**

Please can anyone help me out of this problem.

#### Technical details:

* VS2015,
* .NET Version: 4.5.2

**Comment by christopherseeley** [comment]
We updated our project format, so you'll need VS2017 to add them as reference. If you just want to use the library, you can add the Google.AdWords [nuget package](https://www.nuget.org/packages/Google.AdWords/) instead.
