### ISSUE TITLE
v201802 .NET Client Library Microsoft.Extensions.Configuration error

### ISSUE THREAD

**Issue by addamsviz** [googleads/googleads-dotnet-lib#143]
Hello, 

We attempted to upgrade to v201802 using the Ads API .NET Client Library (adwords_dotnet_lib_v23.1.0):
https://github.com/googleads/googleads-dotnet-lib/releases

We were upgrading from v201708 (adwords_dotnet_lib_v22.1.1) because of the upcoming deprecation schedule and wanted to upgrade to the latest version but we received the below error that seems to be related to Google.Ads.Common:
Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

I see in v23.0.0 (at the above URL) that the Common library was updated with the below item:
Replaced System.Configuration with Microsoft Extension Configuration. Fixes issue #127.

We are using a .NET 4.5.2 console application and it appears that Microsoft.Extensions.Configuration may not be available in .NET 4.5.2.  

Can anyone shed any light on this issue?  For the time being we went ahead and upgraded to v201710 (adwords_dotnet_lib_v22.4.0) to work around the issue and so we won't be impacted by the deprecation at the end of March.

Thank you.

**Comment by AnashOommen** [comment]
Try restoring the nuget packages. MEC comes as a nuget package, so the assembly won't come with the downloads / in github by default.

**Comment by AnashOommen** [comment]
Or if you just need to use the client library, you can add a nuget reference to Google.AdWords package and don't have to compile the assemblies locally.

**Comment by AnashOommen** [comment]
Oh wait - if you are using the binary-only download, MEC is definitely missing there. Could you try using the nuget package instead? https://www.nuget.org/packages/Google.AdWords/23.1.0

I'll keep this bug open to figure out how best to handle the binary download.

**Comment by addamsviz** [comment]
Yes, we are using the binary download (adwords_dotnet_lib_v23.1.0.zip) and normally do not use Nuget packages in our organization.  Is there any way you can include the additional Microsoft.Extensions.Configuration dependency DLL in the binary download?  Also, will this require different settings in the app.config file or will the previous settings in the app.config still work properly?

This is the binary we downloaded:
https://github.com/googleads/googleads-dotnet-lib/releases/download/v23.1.0/adwords_dotnet_lib_v23.1.0.zip

**Comment by AnashOommen** [comment]
The easiest way would be to create a new Console application for .NET 452, add Google.AdWords as a nuget reference, then build it. The Debug/bin folder should have all the DLLs you need. Just copy them over to the lib folder and add references to your project.

**Comment by jskrewson** [comment]
FYI, I'm dealing with the same issue today.  Microsoft.Extensions.Configuration NuGet package will not install in .NET 4.5.2, says it is incompatible.  Your opinion, @AnashOommen is that it will work if we manually add it? I'll give it a try, but its hackalicous.

**Comment by christopherseeley** [comment]
Microsoft.Extensions.Configuration Version [1.1.2](https://www.nuget.org/packages/Microsoft.Extensions.Configuration/1.1.2) is compatible with .NET 4.5.2

**Comment by AnashOommen** [comment]
MEC won't install in a project targeting .NET452 because it only has targets for .NET Standard 2.0. However, that's only for compilation purposes. It has no implication on runtime compatibility.

The dependency in the client librarry right now is like Google.Ads.Common (9.0.0, Compatible with .NET 452, .NET Standard 2.0) => Microsoft.Extensions.Configuration (1.1.2, Compatible with .NET Standard 1.1)

If you see the [compatibility metrics from Microsoft](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/), it says that .NET Standard 1.1 works with .NET SDK 4.5 and above. That means that even though you cannot use MEC for compiling against a project of .NET452, you can use it at runtime if it were pulled as a dependency of another nuget package targeting .NET 452.

So in your case, the fix is to just add reference to Google.AdWords nuget packaage. Nuget will do all the remaining magic and pull down all the dependencies during build.

I'm attaching a Console project targeting .NET 452 to illustrate the usage. App.config is redacted, but you should be able to get it running by substituting your own creds. bin\Debug should have all the DLLs that Nuget pulled down as dependency.

[TestNugetPackageCompat.zip](https://github.com/googleads/googleads-dotnet-lib/files/1789602/TestNugetPackageCompat.zip)

**Comment by AnashOommen** [comment]
And this one directly refers to the dlls downloaded by Nuget (see the lib folder).

[TestDirectDeps.zip](https://github.com/googleads/googleads-dotnet-lib/files/1789672/TestDirectDeps.zip)

**Comment by addamsviz** [comment]
Thank you so much for your assistance, Anash.  Downloading the "TestDirectDeps.zip" file and adding the references to the Microsoft.Extensions DLLs and the Newtonsoft.Json.dll allowed me to compile and I am now running adwords_dotnet_lib_v23.1.0 successfully.

**Comment by jskrewson** [comment]
Agreed, I also added the dll's from testdirectdeps.zip and it worked. NUGET install of the adwords client library on Visual Studio 2012 SP5 (.net 4.5.2) did not work. It seemed like a weird package manager issue, so I just punted and used the attached archive.

**Comment by dmkrause** [comment]
I also had the 'Microsoft.Extensions.Configuration error which is fixed when I installed the .dll's in your TestDirectDep example.
Now I am getting the below error.  It's an existing application that is working in version 201705 and I am calling the ADGROUP_PERFORMANCE_REPORT using the ReportUtilities(User, "v201802", definition).

Do you know what can cause this?  Thanks.

Error...
Message: Method not found: '!!0[] System.Array.Empty()'.
Source:	"Google.Ads.Common"	

StackTrace:   at Google.Api.Ads.Common.Logging.LogEntry.GetFormattedRequestLog(RequestInfo requestInfo, ISet`1 headersToMask, TraceFormatter traceFormatter)     at Google.Api.Ads.Common.Logging.LogEntry.LogRequest(RequestInfo requestInfo, ISet`1 headersToMask, TraceFormatter formatter)     at Google.Api.Ads.Common.Logging.LogEntry.LogRequest(RequestInfo requestInfo, ISet`1 headersToMask)     at Google.Api.Ads.Common.Util.HttpUtilities.WritePostBodyAndLog(WebRequest request, String postBody, String service, LogEntry logEntry, ISet`1 headersToMask)     at Google.Api.Ads.Common.Lib.OAuth2ProviderBase.CallTokenEndpoint(String body)     at Google.Api.Ads.Common.Lib.OAuth2ProviderForApplications.RefreshAccessTokenInOfflineMode()     at Google.Api.Ads.Common.Lib.OAuth2ProviderForApplications.RefreshAccessToken()     at Google.Api.Ads.Common.Lib.OAuth2ProviderBase.RefreshAccessTokenIfExpiring()     at Google.Api.Ads.Common.Lib.OAuth2ProviderForApplications.RefreshAccessTokenIfExpiring()     at Google.Api.Ads.Common.Lib.OAuth2ProviderBase.GetAuthHeader()     at Google.Api.Ads.Common.Lib.OAuth2ProviderForApplications.GetAuthHeader()     at Google.Api.Ads.AdWords.Util.Reports.ReportUtilities.BuildRequest(String downloadUrl, String postBody, LogEntry logEntry)     at Google.Api.Ads.AdWords.Util.Reports.ReportUtilities.DownloadReport(String downloadUrl, String postBody)     at Google.Api.Ads.AdWords.Util.Reports.ReportUtilities.GetReport()     at Google.Api.Ads.Common.Util.Reports.AdsReportUtilities.GetResponse()     at Google.Api.Ads.AdWords.Util.Reports.ReportUtilities.GetResponse()     at GoogleData.ComClass1.ProcessGoogleAds(DateTime dtRunDate) in D:\Agora\Google201802\GoogleData\ComClass1.vb:line 493"	String

**Comment by AnashOommen** [comment]
Could you try adding reference to all the assemblies in the Direct dependency folder?

**Comment by dmkrause** [comment]
I removed an re-added references to everything and to be sure I had the correct versions, I copied all the .dlls in your test programs \lib folder first.
Still the same error.

**Comment by AnashOommen** [comment]
I think the possible reason is explained here: https://stackoverflow.com/questions/31253747/method-not-found-0-system-array-empty-asapp-bundleconfig-registerbundl

I guess I'll have to compile the library on a .NET 452 machine that does not have a .NET46 installation to catch these bugs.

**Comment by dmkrause** [comment]
Hi Anash,
You commented above that "I guess I'll have to compile the library on a .NET 452 machine ".
Did you get a chance to do that?
Thanks.

**Comment by AnashOommen** [comment]
Seems our issue arises as a result of https://github.com/dotnet/sdk/issues/335. We tried compiling using the recommendations on https://github.com/dotnet/sdk/issues/335#issuecomment-371444503, but that leads to this issue, see https://github.com/dotnet/sdk/issues/335#issuecomment-371468353.

Our development happens on a Windows machine, but our build and deployment happens on linux machine. Which explains why we never caught it during development and testing. One must learn to distrust the compiler too, it seems...

https://github.com/dotnet/sdk/issues/335#issuecomment-371484670 seems like a way out. Will try this out tomorrow.

**Comment by AnashOommen** [comment]
This issue should be fixed, see #151.
