### ISSUE TITLE
v201802 .NET Client Library Method not found: 'System.String System.String.Format

### ISSUE THREAD

**Issue by addamsviz** [googleads/googleads-dotnet-lib#144]
Yesterday I submitted the following issue that describes my scenario/configuration (https://github.com/googleads/googleads-dotnet-lib/issues/143).  I encountered another error now after releasing the above updates to my production app server (this error did not occur on my development computer).  The error occurs on the GetService call in the below code. Do I possibly need to include the following DLLs in the application directory on the production server? I did not have these references with my application or in the application directory on my development computer and I do not experience the error on my developer computer but maybe these were still somehow found on my machine in the directory I downloaded them to.
Google.Apis.Auth.dll
Google.Apis.Auth.PlatformServices.dll
Google.Apis.Core.dll
Google.Apis.dll
Google.Apis.PlatformServices.dll

Code:
Dim oUser As New AdWordsUser
Dim mcService As ManagedCustomerService = oUser.GetService(AdWordsService.v201802.ManagedCustomerService)

Error Message:
System.MissingMethodException: Method not found: 'System.String System.String.Format(System.IFormatProvider, System.String, System.Object)'.
at Google.Api.Ads.AdWords.Lib.AdWordsServiceFactory.CheckServicePreconditions(ServiceSignature signature)
at Google.Api.Ads.AdWords.Lib.AdWordsServiceFactory.CreateService(ServiceSignature signature, AdsUser user, Uri serverUrl)
at Google.Api.Ads.Common.Lib.AdsUser.GetService(ServiceSignature serviceSignature, Uri serverUrl)
at Google.Api.Ads.Common.Lib.AdsUser.GetService(ServiceSignature serviceSignature, String serverUrl)
at Google.Api.Ads.Common.Lib.AdsUser.GetService(ServiceSignature serviceSignature)

Thank you.

**Comment by AnashOommen** [comment]
What .NET version are you on?

**Comment by addamsviz** [comment]
Hi Anash, we are using .NET framework version 4.5.2.

**Comment by christopherseeley** [comment]
Yes, those are additional dependencies which you can manage through nuget. I've also updated the binary distribution [download](https://github.com/googleads/googleads-dotnet-lib/releases/download/v23.1.0/adwords_dotnet_lib_v23.1.0.zip) to include all the 4.5.2 dependencies if you prefer that method.

**Comment by addamsviz** [comment]
@AnashOommen  @christopherseeley  I have still not been able to work around this issue.  The issue appears to be that the String.Format call you are using may only be used in .NET 4.6.  See the below article which speaks to this.  On my developer computer I have .NET Framework 4.7.1 (461308) installed but on my production application server only .NET Framework 4.5.2 (379893) installed.  On my developer computer I do not receive the error mentioned but on production I do receive the error.  Per the below article can you update the library to use a String.Format signature that will be recognized by .NET 4.5.2 or update the library to target 4.5.2?
https://stackoverflow.com/questions/30558827/method-not-found-system-string-system-string-formatsystem-iformatprovider-sy
