### ISSUE TITLE
Failed to get campaigns. Exception says "Failed to refresh access token. { "error" : "invalid_grant" }"

### ISSUE THREAD

**Issue by debudeveloper** [googleads/googleads-dotnet-lib#145]
<add key="DeveloperToken" value="8Y0jYEAg52U1d3uYVfSYog" />  **// get this token by manager account ** 
 <add key="ClientCustomerId" value="430-727-2984" /> **// test client adwords account id**

  <add key="OAuth2ClientId" value="94850915492535gt77r5ne4h48rqsi6jd7qnem3nbnuv.apps.googleusercontent.com" />
    <add key="OAuth2ClientSecret" value="qpFU9MrUJb4W9C9o8yp9qOSS" />   // credentials are created by test manager token

  <add key="OAuth2RefreshToken" value="1/b4W3_Zwyfve2j3QCBtiFb3dvLqmLGl9uqhf0gLpdFtE" /> // this access token created through my test master account credentials 

and I test through my Test manager customer id . but shows above error

**Comment by AnashOommen** [comment]
Try generating a fresh refresh token using OAuthTokenGenerator tool and see if that fixes the issue.

**Comment by debudeveloper** [comment]
Thank you , After refresh token its not showing any that type of error.

but while I click "Get Campaign" by my client customer id
get an exception while execute this code 
=> CampaignPage page = service.get(selector);


response is =>Failed to get campaigns. Exception says "The request failed with HTTP status 404: Not Found."
