### ISSUE TITLE
Cannot run samples

### ISSUE THREAD

**Issue by digitalbanana** [googleads/googleads-dotnet-lib#147]
Not sure if Imissed something in the read me but cant samples either through code or via nuget downloaded smaples.

running locally code wont build and error is

`Severity	Code	Description	Project	File	Line	Suppression State
Error		The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.	AdWords.Examples.CSharp.OAuth	C:\Source\googleads-dotnet-lib\src\AdWords\AdWords.csproj	1	
`

running nuget samples is...

`                Dictionary<AttributeType, AdWords.v201708.Attribute> ideas =
                    targetingIdea.data.ToDict();`

Error 
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'AdWords' could not be found (are you missing a using directive or an assembly reference?)		`

Any help greatly appreciated

**Comment by christopherseeley** [comment]
The example download projects now use Visual Studio 2017 project formats. For the nuget example package, it looks like there's a bug in certain examples where the full namespace needs to be referenced.

You can replace `AdWords.v201708.Attribute` with ` Google.Api.Ads.AdWords.v201708.Attribute` in the GetKeywordIdeas examples as a quick fix.

**Comment by digitalbanana** [comment]
Hi @christopherseeley ,

Thanks for swift response, fully qualifying the namespace sorted. Much appreciated.

Cheers

Dave
