### ISSUE TITLE
 For NO client library , What is the definition for the method GetOAuth2AccessToken();

### ISSUE THREAD

**Issue by debudeveloper** [googleads/googleads-dotnet-lib#148]
I have created access token by OAuth client Id and secret , but what about  GetOAuth2AccessToken();

Other think , please look carefully , While I request with no client library , it occur an error ,

The request failed with HTTP status 404: Not found"

when execute this line ,
  WebResponse response = webRequest.GetResponse();
 

my test campaign not activated( because of its a test account) , that is the problem ?

all uses details are bellow :
client id = 430-727-2984
token = 8Y0jYEAg52U1d3uYVfSYog
authid: 190694974839-mrjgodc0l752e8eevkai06qfo69mncrn.apps.googleusercontent.com

secret  : kYPpgAD4CYFTxwmA_w1PSxYA

User agent : "pioneerweb"

**Comment by AnashOommen** [comment]
1. Please reset your developer token, client secret and password. Do not post them on a public thread.
2. Is there a reason why you don't want to use the client library? SOAP is not the easiest protocol to work without an SDK / client library.
3. You need to write the GetOAuth2AccessToken() method, you can start looking at the [OAuth2 playground](https://developers.google.com/oauthplayground/) to see what HTTP calls are involved. You could do step 1 and step 2 manually on the UI, store the refresh token, then then write the code for refreshing access token.

**Comment by debudeveloper** [comment]
Thanks,

Also I'm using client library , But still got same error ,

In OAuth , when I select "Web Application" its takes Java script origin and authorized redirect url
need to put those value ?
