### ISSUE TITLE
Why does ApplicationException not inherit the System.Exception?

### ISSUE THREAD

**Issue by thacake** [googleads/googleads-dotnet-lib#149]
I am using the CampaignPage get(Selector serviceSelector) method 
`		// Summary:
		//     Returns the list of campaigns that meet the selector criteria.
		//
		// Parameters:
		//   serviceSelector:
		//     the selector specifying the Campaigns to return.
		//
		// Returns:
		//     A list of campaigns.
		//
		// Exceptions:
		//   T:Google.Api.Ads.AdWords.v201710.ApiException:
		//     if problems occurred while fetching campaign information.
		public virtual CampaignPage get(Selector serviceSelector);
`
and trying to catch the ApiException that it says it throws, but noticed that it inherits ApplicationException and that class does not inherit System.Exception? In the Java SDK, ApiException inherits the Exception class (https://github.com/googleads/googleads-java-lib/search?utf8=%E2%9C%93&q=class+ApiException&type=).

I know that the AdWordsApiException type has a property object ApiException which I could use to cast into the ApiException type, but that is if AdwordsApiException type was being thrown for the method I am using above.

**Comment by AnashOommen** [comment]
The library actually throws AdWordsApiException, it’s incorrect documentation being generated from the wsdl. See https://github.com/googleads/googleads-dotnet-lib/blob/master/examples/AdWords/CSharp/v201802/ErrorHandling/HandlePolicyViolationError.cs for an example.

As for difference between Java and C# in terms of exception handling: it has roots in the fact that Microsoft code generators don’t generate stubs for soap:Fault, whereas Java code generators do. When this part of the library was written, there were no nice things like Roslyn to rewrite the generated stub, but may be it is possible with today’s technology. I’ll investigate as time permits.

**Comment by AnashOommen** [comment]
Fixed in v23.6.0
