### ISSUE TITLE
App.config won't load if multiple config files are in exe's directory

### ISSUE THREAD

**Issue by jldrci** [googleads/googleads-dotnet-lib#150]
On upgrading to the latest version, our application failed with an OAuth2 configuration error. Looking closer, we see that the `DfpAppConfig` isn't populating from the application's config file and just has the default values.

It looks like [XmlDictionarySectionConfigurationSource](https://github.com/googleads/googleads-dotnet-lib/blob/master/src/Common/Config/XmlDictionarySectionConfigurationSource.cs) is trying to load the configuration from the first .exe.config file it can find, but as we have multiple executables in the same directory, it's trying to load the config from the wrong one, causing the app to fail.

**Comment by AnashOommen** [comment]
Thanks for pointing it out. I guess I have to rethink the approach a bit; I was hoping that my logic in XmlDictionarySectionConfigurationSource would mostly work.

As silly as it might seem, figuring out the current exe name to resolve App.config is not possible in .NET Core. https://github.com/dotnet/core-setup/issues/2007.
