### ISSUE TITLE
v201802 .NET Client Library Method not found: 'System.String System.String.Format

### ISSUE THREAD

**Issue by addamsviz** [googleads/googleads-dotnet-lib#151]
On my original post I was still not able to work around this issue and I could not find a way to re-open my original issue or get a response back so I posted this new issue referencing my original issue:
https://github.com/googleads/googleads-dotnet-lib/issues/144

I have still not been able to work around this issue. The issue appears to be that the String.Format call you are using may only be used in .NET 4.6. See the below article which speaks to this. On my developer computer I have .NET Framework 4.7.1 (461308) installed but on my production application server only .NET Framework 4.5.2 (379893) installed. On my developer computer I do not receive the error mentioned but on production I do receive the error. Per the below article can you update the library to use a String.Format signature that will be recognized by .NET 4.5.2 or update the library to target 4.5.2?
https://stackoverflow.com/questions/30558827/method-not-found-system-string-system-string-formatsystem-iformatprovider-sy

**Comment by christopherseeley** [comment]
The library does [target](https://github.com/googleads/googleads-dotnet-lib/blob/master/src/AdWords/AdWords.csproj#L22) .NET 4.5.2.

A couple questions:
1. Are you building the library from source or using the binary (or nuget) distribution?
2. If you're not using nuget, does using nuget resolve the issue?

**Comment by addamsviz** [comment]
@christopherseeley  I am using the library from binary distribution that was provided in the the "TestDirectDeps.zip" file that @AnashOommen provided on this issue:  https://github.com/googleads/googleads-dotnet-lib/issues/143

We do not normally do not use Nuget packages in our organization but I am confident this will not fix the issue I have listed here since this is caused by a .NET framework 4.5.2 conflict when .NET 4.6 is not installed.  My issue sounds similar to the issue that dmkrause had and @AnashOommen  responded to yesterday where Anash mentioned "I guess I'll have to compile the library on a .NET 452 machine that does not have a .NET46 installation to catch these bugs.".

**Comment by christopherseeley** [comment]
I'm getting a machine configured to reproduce this, but in the meantime does building from source on a machine without 4.6+ fix the problem?

**Comment by christopherseeley** [comment]
I was able to reproduce, and confirmed that building from source on a machine without 4.6+ is a workaround. I'm working on a fix now.

**Comment by christopherseeley** [comment]
Fixed in [v23.1.1](https://github.com/googleads/googleads-dotnet-lib/releases/tag/v23.1.1).

**Comment by addamsviz** [comment]
I was able to get my .NET 4.5.2 application running properly in my dev and production environments using v23.1.1 and referencing the Microsoft.Extensions related DLLs provided in the "TestDirectDeps.zip" provided in issue 143 (https://github.com/googleads/googleads-dotnet-lib/issues/143).
