### ISSUE TITLE
NOT_ADS_USER error after upgrading to latest package version

### ISSUE THREAD

**Issue by stevehjohn** [googleads/googleads-dotnet-lib#152]
Hi,
I have full fat .net project using v22.3.1 calling AdWords as a service account.
Now that there is .net core support, I created a new project using v23.1.0. Using the same credentials, I get an error back: NOT_ADS_USER.
Just to ensure I hadn't missed something in my new implementation, I upgraded the original project to the latest package version and it started having the same issue.
Are there any know issues?
Thanks in advance,
Steve.

**Comment by RomanNikolaychuk** [comment]
Hi all,

We have the same problem.
After upgrade to the latest Version of Library (Adwords 201802) our brave project stopped to work.

**AdWordsApiException: Exception of type 'Google.Api.Ads.AdWords.Lib.AdWordsApiException' was thrown. 
User in the cookie is not a valid Ads user.. (Error: AuthenticationError.NOT_ADS_USER, FieldPath: , Trigger: <null>)**


> Server stack trace: 
>    at Google.Api.Ads.Common.Lib.SoapFaultInspector`1.AfterReceiveReply(Message& reply, Object correlationState)
>    at System.ServiceModel.Dispatcher.ImmutableClientRuntime.AfterReceiveReply(ProxyRpc& rpc)
>    at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
>    at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
>    at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
>    at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
> 
> Exception rethrown at [0]: 
>    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
>    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
>    at Google.Api.Ads.AdWords.v201802.CampaignServiceInterface.get(Selector serviceSelector)
>    at Google.Api.Ads.AdWords.v201802.CampaignService.get(Selector serviceSelector) 

Please help!

Best regards,
Roman Nikolaychuk.

**Comment by AnashOommen** [comment]
We've identified the issue, it's that we are not setting the PrnEmail [here](https://github.com/googleads/googleads-dotnet-lib/blob/master/src/Common/Lib/OAuth2ProviderForServiceAccounts.cs#L107). Fix coming in next push.

**Comment by stevehjohn** [comment]
Thanks for the prompt investigation and response.

**Comment by christopherseeley** [comment]
Fixed in [v23.1.1](https://github.com/googleads/googleads-dotnet-lib/releases/tag/v23.1.1).

**Comment by stevehjohn** [comment]
FYI, have tested the latest version and it is fixed. Thanks for the prompt action.
