### ISSUE TITLE
v201802:Could not load file or assembly 'System.ServiceModel.Primitives or one of its dependencies.The system cannot find the file specified.

### ISSUE THREAD

**Issue by Saritha535** [googleads/googleads-dotnet-lib#153]
Hello,

I  upgrade to v201802 using the Ads API .NET Client Library (adwords_dotnet_lib_v23.1.0):
https://github.com/googleads/googleads-dotnet-lib/releases

We are upgrading from v201705 (adwords_dotnet_lib_v22.1.1) because of the upcoming deprecation schedule and wanted to upgrade to the latest version but got the below error 

**Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.**

We are using a .NET 4.5.2 console application, .Net Standard 2.0.
Please assist me to solve this issue asap because the depreciation date is on March28th.

**Comment by AnashOommen** [comment]
See https://github.com/googleads/googleads-dotnet-lib/issues/143 for an attachment named TestDirectDeps.zip. That should have all the binaries you need.

My recommendation is, if you do not edit the source code for the AdWords project itself, try adding a Nuget reference to Google.AdWords and delete the downloaded source reference from your project. It's really much simpler that way. Trying to manually resolve every single Nuget reference by manually downloading DLLs is not a very productive way for your application development.

**Comment by Saritha535** [comment]
I added reference from nuget and I deleted the downloaded source reference.
But As mention in this article https://github.com/googleads/googleads-dotnet-lib/wiki/Upgrading-your-client-library-to-v22.0.0 
 Support for SoapListenerExtension  in v23.1.0 has been removed. And last response and last request also removed .So I am using these in my project. 

I am getting these errors in my project.
**'AccountLabelService' does not contain a definition for 'LastRequest' and no extension method 'LastRequest' accepting a first argument of type 'AccountLabelService' could be found (are you missing a using directive or an assembly reference?)	

'TrafficEstimatorService' does not contain a definition for 'LastRequest' and no extension method 'LastRequest' accepting a first argument of type 'TrafficEstimatorService' could be found (are you missing a using directive or an assembly reference?)	**

Please could assist how to solve this problem

**Comment by Saritha535** [comment]
I added reference from nuget package and deleted downloaded adwords .csproj.
When I am trying to add adwords account in my application. I am getting below error.
Please could anyone help me to solve this issue.

![erro](https://user-images.githubusercontent.com/37066080/37696406-4920089e-2cfc-11e8-9405-d6f7e5eccdf1.PNG)

**Comment by Saritha535** [comment]
I am eagerly waiting for response. The AdWords API depreciation deadline is much closer. Still I am facing issues in up-gradation. I added reference of System.ServiceModel.Primitives latest v4.4.1 from nuget package, even though I am getting the above error.
 Please give any idea to solve this issue.

**Comment by AnashOommen** [comment]
I think we can take one of the two ways out.
1. I can send you a basic Visual Studio workspace for a console project, complete with all the nuget references and latest format. You can copy over your project files into that csproj and compile.

2. Upgrade to version 22.3.0 of the client library, and migrate to v201710. Deal with v201802 migration later. 

Which one would you prefer?

**Comment by Saritha535** [comment]
I already tried option 2. I migrated to v201702 but same exception came.
Please could help with option 1.
Please reply asap.

**Comment by Saritha535** [comment]
**Thanks Anash**
I tried to upgrade to version 22.3.0 of the client library and migrated to v201710 working fine. But when I am added reference from nuget package its not worked some issue came.  Then again I downloaded the files from github and added to project its worked fine. As of now I am upgraded v201710 later I will work on v201802.
Please look at the issue of v201802 why it's not worked.

**Comment by AnashOommen** [comment]
Hi Saritha,

One way to address the issue would be for me to create a .NET Console project with all the nuget packages set correctly, and you can copy over your source code into that csproj to make sure it works. Is that something you are open to?

Tx
Anash

**Comment by AnashOommen** [comment]
Closing this issue for now, pls reopen if the issue persists.
