### ISSUE TITLE
Changes to inactive AdWords accounts

### ISSUE THREAD

**Issue by Esbe** [googleads/googleads-dotnet-lib#154]
According to the following blog post (http://googleadsdeveloper.blogspot.ca/2018/03/changes-to-inactive-adwords-accounts.html), it looks like the behavior of API calls will change on March 26th after many accounts are cancelled.

The documentation there mentions the following:

> Any AdWords API request that specifies the account's customer ID in the clientCustomerId header will fail with an OperationAccessDenied error and a reason of CUSTOMER_NOT_ACTIVE starting with v201802, and a reason of ACTION_NOT_PERMITTED for earlier versions of the AdWords API.

However, the latest version of the .Net library does **not** contain `CUSTOMER_NOT_ACTIVE` as a valid enum value in `Google.Api.Ads.AdWords.v201802.OperationAccessDeniedReason`.

Will there be a new version of the library before that date ? If so, isn't that a contract breaking change ?
Otherwise, won't the current 23.1.0 library start throwing deserialization exceptions if the API really starts sending that reason ?

**Comment by AnashOommen** [comment]
Hi Esbe,

It's AuthorizationErrorReason. CUSTOMER_NOT_ACTIVE, and that error is in v201802 stubs. I'll ask Josh to clarify the blog post. Thanks for pointing it out.

Cheers
Anash
