### ISSUE TITLE
AdWordsAppConfig Not Using configSource File

### ISSUE THREAD

**Issue by ryanoshag** [googleads/googleads-dotnet-lib#158]
After updating our client library recently, our app started failing with OAuth2 configuration errors. Further inspection revealed that configurations provided in a separate file and referenced using the _configSource_ property in _app.config_ (as detailed [here](https://github.com/googleads/googleads-dotnet-lib/wiki/Specifying-separate-App.config-for-client-library)) are no longer loaded (as of 23.0.0). 

In previous versions, _AppConfigBase_ used the _ConfigurationManager.GetSection(sectionName)_ method to load the _AdWordsApi_ section, which will pull in the _configSource_ data automatically.

In versions >= 23.0.0, the new _XmlDictionarySectionConfigurationProvider_ class is used to read in configuration data, and does not handle any configurations referenced through the _configSource_ property.

**Comment by AnashOommen** [comment]
Could you temporarily put this in your App.config as a workaround? I'll provide a fix in an upcoming version.

**Comment by ryanoshag** [comment]
We can't really put it in our _App.config_, since we substitute out the AdWords configuration file based on the environment we're running in.

I was able to temporarily fix the issue on our end by loading the configuration in our code and passing a dictionary of config items to the _AdWordsUser_ constructor.

This isn't ideal, however, so a fix would be much appreciated.

**Comment by christopherseeley** [comment]
Fixed in v23.3.0
