### ISSUE TITLE
Review Ad Extensions in v201802

### ISSUE THREAD

**Issue by aukevin** [googleads/googleads-dotnet-lib#161]
Are Review Ad Extensions supported in v201802?

It looks like they [still exist as an ExtensionFeedItem](https://developers.google.com/adwords/api/docs/reference/v201802/CampaignExtensionSettingService.ReviewFeedItem), but when I query the [CampaignFeedService](https://developers.google.com/adwords/api/docs/reference/v201802/CampaignFeedService.CampaignFeed) I don't see any feeds with [placeholder type 8](https://developers.google.com/adwords/api/docs/appendix/placeholders#review). To double check, tried to access the ReviewFeedItem for my campaign from the CampaignExtensionSettingService (v20180) using the same campaignId and was successful. In addition, I can the campaignFeed from v201710.

Is this the intended behavior?

**Comment by AnashOommen** [comment]
Hi,

Could you pls repost on the API forum? https://groups.google.com/forum/#!forum/adwords-api.
Apologies for the delay in responding.

Cheers
Anash
