### ISSUE TITLE
Remove dependency on BouncyCastle in examples library.

### ISSUE THREAD

**Issue by MaverickMartyn** [googleads/googleads-dotnet-lib#162]
BouncyCastle isn't .NET Standard compatible in the examples library as of version 23.2.0.
Related but not the same issue: https://github.com/googleads/googleads-dotnet-lib/issues/125

**Comment by jimper** [comment]
Thanks for flagging this. We removed the dependency for this project in v23.0.0, but missed cleaning up a reference in the nuspec. We'll have a fix out for this in the next release.

**Comment by christopherseeley** [comment]
Fixed in v23.3.0
