### ISSUE TITLE
No longer getting error text, just generic "exception" messages

### ISSUE THREAD

**Issue by dgjohnson83** [googleads/googleads-dotnet-lib#165]
Hello,

We recently updated our API versions to v201802, and since that time we no longer receive error message text, just a generic "exception of type 'Google.Api.Ads.Dfp.Lib.DfpApiException'".  In the test case I am using, it should return "[UniqueError.NOT_UNIQUE @ lineItem[0].name".

Is there something I need to change in our code to get the error text now?  Or some option that needs to be enabled in the app.config?

Current library versions: Google.Api is v1.32, Google.Dfp is 23.2.

Thank you

**Comment by christopherseeley** [comment]
The error text is available in the inner ApiException's message property:
https://github.com/googleads/googleads-dotnet-lib/blob/master/src/Dfp/Lib/DfpApiException.cs#L39

We could make this easier to access as an enhancement.

**Comment by AnashOommen** [comment]
Fixed in v24.3.0
