### ISSUE TITLE
AccountLabelService

### ISSUE THREAD

**Issue by bbatton** [googleads/googleads-dotnet-lib#166]
AccountLabelPage class seems to be missing from the v201802 build, has this been deprecated?

**Comment by AnashOommen** [comment]
I think the code generator flattened that class and the AccountLabelService class method looks like:

AccountLabel[] get(Selector selector) {

Let me know if it doesn't work for you, and I can fix up the code generator.

**Comment by AnashOommen** [comment]
Sure, I'll fix this in the next release.

**Comment by AnashOommen** [comment]
Fixed in 23.5.0
