### ISSUE TITLE
Google.AdWords set WebRequest.DefaultWebProxy

### ISSUE THREAD

**Issue by razinalexrazinalex** [googleads/googleads-dotnet-lib#168]
Hello, i use Google.AdWords through proxy server. 
This is short sample of my code:

```
AdWordsUser user = new AdWordsUser();
AdWordsAppConfig config = (AdWordsAppConfig)user.Config;
config.ClientCustomerId = ClientCustomerId;			
config.UserAgent = "AdWordsApi";
/*Set auth keys ...*/
config.OAuth2Mode = OAuth2Flow.APPLICATION;
var proxy = new WebProxy(ip, port);
proxy.Credentials = new NetworkCredential(ProxyUser, ProxyPassword);
config.Proxy = proxy;

CampaignService campaignService = (CampaignService)user.GetService(AdWordsService.v201802.CampaignService);
```

After last row i see that static property WebRequest.DefaultWebProxy is set to this proxy. How can i prevent this? I want use this proxy only for Google.AdWords and not for other web requests.

**Comment by christopherseeley** [comment]
You could set the proxy on the underlying WCF client instead of through the setter. Here's where this is happening:
https://github.com/googleads/googleads-dotnet-lib/blob/master/src/Common/Lib/AdsSoapClient.cs#L94

This stackoverflow post shows an example of this:
https://stackoverflow.com/questions/17968307/how-to-set-proxy-credentials-to-specific-wcf-client

**Comment by razinalexrazinalex** [comment]
Thank you, i will try. Have you got any instruction how to build project? I open in in visual studia 2017 and have a lot of errros like 	_The current .NET SDK does not support targeting .NET Core 2.0.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0.	OAuthTokenGenerator	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets_

i want build it in 4.5

**Comment by christopherseeley** [comment]
You don't need to build from source to set the proxy - all the properties are public. If you do want to build, the library requires the .NET Core SDK since it supports both 4.5 and .NET Standard 2.0

**Comment by razinalexrazinalex** [comment]
I don't understand your words about _You don't need to build from source to set the proxy - all the properties are public._

I can use SetProxySettings<TChannel> on created CampaignService.
But what to do, when i use ReportUtilities? I see in HttpUtilities.cs that it also use proxy from config

>       WebRequest request = HttpWebRequest.Create(url);
>       request.Method = method;
>       request.Proxy = config.Proxy;
>       request.Timeout = config.Timeout;

So i must use setter Proxy to Config

**Comment by razinalexrazinalex** [comment]
Soon i have problm with build. i download adwords_dotnet_lib_v23.4.1.zip from https://github.com/googleads/googleads-dotnet-lib/releases
and there are only two dll - Google.AdWords.dll and Google.Ads.Common.dll
But when i build AdWords.sln it is additional Google.Apis.Core.dll. Why?

**Comment by razinalexrazinalex** [comment]
Yes, Thank you.
