### ISSUE TITLE
Missing Selector paging setting on example code

### ISSUE THREAD

**Issue by 1150Rich** [googleads/googleads-dotnet-lib#169]
https://developers.google.com/adwords/api/docs/samples/csharp/optimization#get-keyword-ideas

Is missing 

selector.paging = Paging.Default;

which results in an error when you run the code
Adding the code after you have created the selector object clears the error.

<soap:Fault>
      <faultcode>soap:Server</faultcode>
      <faultstring>[TargetingIdeaError.NO_PAGING_IN_SELECTOR @ selector, RequiredError.REQUIRED @ selector.paging]</faultstring>
      <detail>
        <ApiExceptionFault xmlns="https://adwords.google.com/api/adwords/o/v201802" xmlns:ns2="https://adwords.google.com/api/adwords/cm/v201802">
          <ns2:message>[TargetingIdeaError.NO_PAGING_IN_SELECTOR @ selector, RequiredError.REQUIRED @ selector.paging]</ns2:message>
          <ns2:ApplicationException.Type>ApiException</ns2:ApplicationException.Type>
          <ns2:errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="TargetingIdeaError">
            <ns2:fieldPath>selector</ns2:fieldPath>
            <ns2:fieldPathElements>
              <ns2:field>selector</ns2:field>
            </ns2:fieldPathElements>
            <ns2:trigger></ns2:trigger>
            <ns2:errorString>TargetingIdeaError.NO_PAGING_IN_SELECTOR</ns2:errorString>
            <ns2:ApiError.Type>TargetingIdeaError</ns2:ApiError.Type>
            <reason>NO_PAGING_IN_SELECTOR</reason>
          </ns2:errors>
          <ns2:errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns2:RequiredError">
            <ns2:fieldPath>selector.paging</ns2:fieldPath>
            <ns2:fieldPathElements>
              <ns2:field>selector</ns2:field>
            </ns2:fieldPathElements>
            <ns2:fieldPathElements>
              <ns2:field>paging</ns2:field>
            </ns2:fieldPathElements>
            <ns2:trigger></ns2:trigger>
            <ns2:errorString>RequiredError.REQUIRED</ns2:errorString>
            <ns2:ApiError.Type>RequiredError</ns2:ApiError.Type>
            <ns2:reason>REQUIRED</ns2:reason>
          </ns2:errors>
        </ApiExceptionFault>
      </detail>
    </soap:Fault>
  </soap:Body>
</soap:Envelope>

**Comment by AnashOommen** [comment]
Fixed in 23.5.0
