### ISSUE TITLE
OAuth2ProviderForApplications.GetAuthorizationUrl() / Error : OAuth 2 parameters can only have a single value: response_type

### ISSUE THREAD

**Issue by jesuissur** [googleads/googleads-dotnet-lib#173]
Hi

We're using the v23.5.0 release and when we call `OAuth2ProviderForApplications.GetAuthorizationUrl()`, the generated Url contains duplicate OAuth information and we got a 400 error code when we call the url with the following message:
> OAuth 2 parameters can only have a single value: response_type

Generated Url:
`https://accounts.google.com/o/oauth2/auth?access_type=offline&state&response_type=code&client_id=INSERT_OAUTH2_CLIENT_ID_HERE&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadwords?access_type=offline&response_type=code`

**Comment by narendramohans** [comment]
Hi Christopher 
any update on the fix ?

**Comment by christopherseeley** [comment]
Fixed in v23.5.1
