### ISSUE TITLE
Criterion Data

### ISSUE THREAD

**Issue by bbatton** [googleads/googleads-dotnet-lib#174]
Version: v201802
Service: CampaignCriterionService
Issue Level: Criterion
Issue: When pulling data from the API the following data always comes back as a null for the represented criterion types as not all types have this issue. I have looked into AdWords to verify that this data shouldn't be null for keywords, placement, location, or platform.

Platform Criterion Type:  Platform Name Field
Location Criterion Type:  Location Name Field
Keyword Criterion Type: Text Field
Placement Criterion Type: Url Field

**Comment by AnashOommen** [comment]
Could you attach a sanitized SOAP request / response xml or a few requestids? I can take a look.

**Comment by bbatton** [comment]
Can I send a JSON of the library response?

**Comment by bbatton** [comment]
Thanks for the instructions, I will follow through and give some data soon

**Comment by bbatton** [comment]
![keyword criterion capture](https://user-images.githubusercontent.com/5585943/42904130-059c1870-8aa2-11e8-8f32-69867b80afe4.png)

**Comment by AnashOommen** [comment]
You need to specify the list of fields you need when building the selector. See https://github.com/googleads/googleads-dotnet-lib/blob/master/examples/AdWords/CSharp/v201806/BasicOperations/GetKeywords.cs#L75 for an example.
