### ISSUE TITLE
Ad Schedule Minute Time

### ISSUE THREAD

**Issue by bbatton** [googleads/googleads-dotnet-lib#178]
Library Version: V201802
Operation Service: Campaign Criterion Service
Class: AdSchedule
Property: StartMinute, End Minute
Desc: Both the start minute and end minute both are suppose to be settable in 15-minute increments with both properties. If set on either the call with fail with an XML parse failure with the inner exception response that minutes of any interval are not allowed.

**Comment by bbatton** [comment]
For Each day As DayOfWeek In week
                adSchedule = New AdSchedule With {
                    .dayOfWeek = day,
                    .startHour = 5,
                    .startMinute = 15,
                    .endHour = 18,
                    .endMinute = 45
                }

                critSchedule = New CampaignCriterion With {
                    .campaignId = campaignId,
                    .CampaignCriterionType = CriterionType.AD_SCHEDULE,
                    .criterion = adSchedule
                }

                operation = New CampaignCriterionOperation With {
                    .operator = [Operator].ADD,
                    .operand = critSchedule
                }

                schedule.Add(operation)
            Next

**Comment by AnashOommen** [comment]
startMinute and endMinutes are enums, not numbers.

See https://developers.google.com/adwords/api/docs/reference/v201806/CampaignCriterionService.AdSchedule#startminute
