### ISSUE TITLE
Report Format Settings

### ISSUE THREAD

**Issue by Gumdro** [googleads/googleads-dotnet-lib#179]
Library Version: V201802
Service: Reports
Report Type: CSV
Property: SkipColumnHeader
Desc: Changing this variable to True or False doesn't change if the column header information is present in the report or not. It always skips including the column header information.

**Comment by bbatton** [comment]
I have changed the settings in both web.config & at runtime with the same result.

**Comment by christopherseeley** [comment]
AdWords API has been turned down and replaced by the Google Ads API, closing as stale.
