### ISSUE TITLE
Lightbox ad

### ISSUE THREAD

**Issue by Dustymcp** [googleads/googleads-dotnet-lib#180]
Hello Friends
Im looking into how to making the new lightbox ad from the api, is this not supported in the client library i cant seem to find any examples.

What i did find was an article pointing to it being a rich media ad but i cant seem to wrap my head around how it would work since i cant parse in text/images on that endpoint, could anyone point me in the right direction? 

Cheers!

**Comment by AnashOommen** [comment]
Hi,

I don't think lightbox ad is a format that is exposed through AdWords API right now.

**Comment by Dustymcp** [comment]
> Hi,
> 
> I don't think lightbox ad is a format that is exposed through AdWords API right now.

Do you know if it will be a supported ad in the api in the near future, its very complicated at the moment to figure out what is availible and what is not, is there any comparison list from UI-API ?

Thanks.
