### ISSUE TITLE
Failed to refresh access token

### ISSUE THREAD

**Issue by trongluc80** [googleads/googleads-dotnet-lib#181]
Hi all

When I updated from v201802 to v201806, I have the problem with Oauth. Code run well in v201802, but not run in v201806.

Detail message : {Error:"invalid_client", Description:"The OAuth client was not found.", Uri:""}
{"Failed to refresh access token."}

My Code :

AdWordsUser user = new AdWordsUser();
AdWordsAppConfig config = new AdWordsAppConfig();
OAuth2ProviderForApplications oAuth = new OAuth2ProviderForApplications(config);
user.OAuthProvider = oAuth;
 user.OAuthProvider.RefreshAccessToken();  => This code line make error
 (user.Config as AdWordsAppConfig).ClientCustomerId = "xxx";
 (user.Config as AdWordsAppConfig).DeveloperToken = "xxx";

pls help me resolve it

Thanks & Br
Luc
![1](https://user-images.githubusercontent.com/41570178/45284186-0b60e500-b50a-11e8-96c6-7b18dab0448a.png)
![2](https://user-images.githubusercontent.com/41570178/45284187-0bf97b80-b50a-11e8-9d84-d672f61b2412.png)

**Comment by bbatton** [comment]
I am having the same issue once updated from v201802 to v201806. Failed to refresh access token, please advise

**Comment by AnashOommen** [comment]
From the error, it looks like OAuth2ClientId is null. It should either be coming from App.config, or you should be setting it at runtime.

Could you put a breakpoint after `AdWordsAppConfig config = new AdWordsAppConfig();` and make sure the config gets picked up from App.config / Web.config?

**Comment by trongluc80** [comment]
Hi

I fix it as the steps below
- Assume you have a project A. Replicate the project to B
- use B and get DLL of v201806 byNuget. Ref https://www.nuget.org/packages/Google.AdWords/24.0.0 
Install-Package Google.AdWords -Version 24.0.0
- Copy all dll that you need to origin project A. Build project

It ok with me

Good luck
Trong Luc
