### ISSUE TITLE
Question: SDK for v201809

### ISSUE THREAD

**Issue by ducaihua** [googleads/googleads-dotnet-lib#183]
Sorry for posting a question here as I didn't find a good place to raise the SDK specific questions.

It looks like AdWords API shipped v201809 but we don't have SDK to support it yet. I assume we will have this new SDK for v201809 soon. Please let me know if I am wrong. Thank you!

**Comment by christopherseeley** [comment]
Support was added in [v24.1.0](https://github.com/googleads/googleads-dotnet-lib/releases/tag/v24.1.0)
