### ISSUE TITLE
Values are always 0 when performing EstimateKeywordTraffic demo

### ISSUE THREAD

**Issue by ductai230894** [googleads/googleads-dotnet-lib#184]
I run the demo app with  v201809.EstimateKeywordTraffic but the average CPC, ad position, daily clicks, daily cost is always 0 whether I use any keyword.

![image](https://user-images.githubusercontent.com/29032100/46100812-8e658900-c1f4-11e8-8230-39f523260a1b.png)

**Comment by christopherseeley** [comment]
This looks like an issue with the API itself rather than the .NET client library. Would you mind posting in the [AdWords API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?

Thanks!
