### ISSUE TITLE
Soap Logging Not Working

### ISSUE THREAD

**Issue by Nilesailor** [googleads/googleads-dotnet-lib#185]
I'm utilizing v24.1.0 of the Adwords .NET library (which is working great by the way).  

I attempted to turn on SOAP logging in order to share logs with Google to troubleshoot an issue, but no log files are being created.  I added the app.config settings per the instructions located here:
https://github.com/googleads/googleads-dotnet-lib/wiki/How-to-capture-SOAP-messages 

I set the "InitializeData" property to an existing directory (and also tested various existing directories).  I've attempted both the "Error" and "Information" settings for logging.  Neither causes logs to be created.  

Any guidance would be appreciated.

**Comment by Nilesailor** [comment]
Never mind... I got it working.  I was reading through the other issues and discovered this open issue with the solution in one of the comments.  

https://github.com/googleads/googleads-dotnet-lib/issues/123

Google simply needs to update their instructions as the help doc no longer matches the client library.

**Comment by christopherseeley** [comment]
Thanks for pointing this out - I updated the wiki with the latest source names.
