### ISSUE TITLE
ResponsiveSearchAd breaks HTML Encoding

### ISSUE THREAD

**Issue by Nilesailor** [googleads/googleads-dotnet-lib#186]
In the attached Request/Response, I created a new ResponsiveSearchAd.  For the 5th "headlines" element, my TextAsset had a non-encoded ampersand.  The client library correctly HTML encoded that ampersand when it generated the SOAP request.

In the fourth "descriptions" element, my TextAsset was created with the ampersand already HTML-encoded.   Instead of leaving it as is, the client library HTML-encoded the leading "&" of the HTML-encoding.  Therefore, "&amp;" became"&amp;amp;"

I've never had this issue with ExpandedTextAds, so I just ran a couple tests.  When the ExpandedTextAd contains HTML encoded entities, the client library correctly generates the SOAP request without attempting to encode them again.  If the strings contain characters such as the ampersand that are not already HTML encoded, the client library correctly HTML encodes them when generating the SOAP request.
[request_info_20181012a.log](https://github.com/googleads/googleads-dotnet-lib/files/2473134/request_info_20181012a.log)

**Comment by christopherseeley** [comment]
AdWords API has been turned down and replaced by the Google Ads API. Closing as stale.
