### ISSUE TITLE
Can't enable detailed logging in .NET client DFP API

### ISSUE THREAD

**Issue by hvallejonine** [googleads/googleads-dotnet-lib#188]
Hi team
 
I am trying to enable SOAP logging for my .NET client application but the detailed log is always empty. The summary log does get populated but it does not have the SOAP Request nor Response. I would guess that the detailed logs would have the full SOAP request/response, is that right? If not, then what would be the best way to capture the raw soap XML messages? I need to troubleshoot an automated process that runs at 3 AM and I can't leave Fiddler running all night because it  sometimes disconnects when the proxy changes for some reason, I'd like to enable logging at the application level
 
Anyway, I followed the directions in the API documentation to enable logging and this is my app.config: `<system.diagnostics>
    <sources>
      <source name="AdsClientLibs.DeprecationMessages"  switchName="AdsClientLibs.DeprecationMessages" switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="myListener" type="System.Diagnostics.EventLogTraceListener" initializeData="Application"/>
        </listeners>
      </source>
      <source name="AdsClientLibs.DetailedRequestLogs"   switchName="AdsClientLibs.DetailedRequestLogs"   switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="detailedRequestLogListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="C:\Logs\Dfp\detailed_logs.log"/>
          <remove name="Default"/>
        </listeners>
      </source>
      <source name="AdsClientLibs.SummaryRequestLogs" switchName="AdsClientLibs.SummaryRequestLogs"   switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="summaryRequestLogListener" type="System.Diagnostics.TextWriterTraceListener"   initializeData="C:\Logs\Dfp\summary_logs.log"/>
          <remove name="Default"/>
        </listeners>
      </source>
    </sources>
    <switches>
      <add name="AdsClientLibs.DeprecationMessages" value="Information" />
      <add name="AdsClientLibs.DetailedRequestLogs" value="Information" />
      <add name="AdsClientLibs.SummaryRequestLogs" value="Information" />
    </switches>    
    <trace autoflush="true" />
 </system.diagnostics>`

I made two basic calls from the client to different services of the API. This is what was logged in the summary log file:
 
_AdsClientLibs.SummaryRequestLogs Information: 1 : Request made: Host: ads.google.com, Service: AudienceSegmentService, Method: getAudienceSegmentsByStatement, networkCode: , Request ID: 319d7a06e64bc301687faf46d309861b, ResponseTime(ms): 778, OperationsCount: 0, IsFault: False, FaultMessage: 
AdsClientLibs.SummaryRequestLogs Information: 1 : Request made: Host: ads.google.com, Service: CompanyService, Method: getCompaniesByStatement, networkCode: , Request ID: f775031c604bf6893da28f0320f0e7a1, ResponseTime(ms): 306, OperationsCount: 0, IsFault: False, FaultMessage:_ 
 
 
But the detailed log file is always empty. The file is created by is never populated
What am I missing??
 
Cheers
Hugo

**Comment by AnashOommen** [comment]
Hi Hugo,

Could you try setting this to ```<add name="AdsClientLibs.DetailedRequestLogs" value="All" />```?

**Comment by AnashOommen** [comment]
Marking as resolved for now. Feel free to reopen if the issue persists.
