### ISSUE TITLE
Device column in some reports returns blanks

### ISSUE THREAD

**Issue by AdrianPell** [googleads/googleads-dotnet-lib#192]
Just noticed that a number of my reports (Ad Group Performance and others) are coming back with blanks in the Device column when segmented by device.

Correlating with the Google Ads UI, it seems that there is a new device type "TV screens" which is coming through that way.  I presume that this will get fixed in the next version of the API, but it doesn't seem very friendly.  I'd have expected "Other" ... but perhaps that has a specific meaning, since I'm seeing that as well.

**Comment by AdrianPell** [comment]
It looks today as if this has changed and the "TV screens" data is now aggregated with "Computers".

I presume that the new device type will show up in the next version of the API?

**Comment by christopherseeley** [comment]
This looks like an issue with the API itself rather than the .NET client library. Would you mind posting in the[ AdWords API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?

Thanks!
