### ISSUE TITLE
Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=1.1.2.0

### ISSUE THREAD

**Issue by bbeda** [googleads/googleads-dotnet-lib#193]
My app targets NET 4.7.2 and uses has Google.Adds.Common 9.3.1 installed.
We also use Microsoft.Extensions.Configuration 2.1.1 in the same assembly. The problem is Google.Adds.Common depends on Micosoft.Extensions.Configuration >=1.1.2 so it thorws this at runtime

_System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.'_

Is there any solution except hoping for an update on Google.Adds.Common to target Net Standard 2.0?

Thank you

**Comment by bbeda** [comment]
Hi @AnashOommen Sorry to bug you but we've got an app feature that is not working because of this. When is the next scheduled release for Google.Adds.Common? Can it be made so that it depends on Microsoft.Extensions.Configuration 2.1.1 instead of 1.1.2 ? Thanks

**Comment by AnashOommen** [comment]
Hi Beda,

Try adding an assembly binding redirect like this:

```xml
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Configuration.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.1.1.0" newVersion="2.1.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Configuration" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.1.1.0" newVersion="2.1.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

Google.Ads.Common supports .NET Standard 2.0 and .NET452. To fix the issue you mentioned, we need to bump the .NET SDK version to .NET461, which would require us to do a major version bump and extensive testing. That's something we don't plan to do in the immediate future.

**Comment by bbeda** [comment]
Well...adding the Binding Redirect solved the problem. So thank you for that. Now what I am confused about is the fact that the App is NET 4.7.2 with AutoGenerate Binding Redirects on so we explicitly removed the binding redirects expecting the framework to do its job. Thanks
