### ISSUE TITLE
No proxy support under .NET Core 2.2

### ISSUE THREAD

**Issue by arnamq** [googleads/googleads-dotnet-lib#201]
Hi,

My project uses .NET Core 2.2 under CentOS Lunux (docker) and it seems that a client library ignores env proxy settings (http_proxy & https_proxy). The OAuth authorization (ADUser) uses a proxy settings but ReportJob ignores it.

Kind regards,
Piotr

**Comment by arnamq** [comment]
I've found couse ot the problem. AdManager library has reference to the System.ServiceModel.Http 4.4.2 and there was a bug with a proxy support in that version. If I force my app tu use System.ServiceModel.Http 4.5 everything works fine.

Could you please update the dependencies to use the newset version of System.ServiceModel.Http?

**Comment by christopherseeley** [comment]
Duplicate of #133
