### ISSUE TITLE
GetCustomers() not working

### ISSUE THREAD

**Issue by groverp93** [googleads/googleads-dotnet-lib#203]
Hello team,
We are using google Ads api for offline conversation tracking. We are uploading conversations  into our clients AdWords accounts. Our customers wants to integrate their account with different customer id's in our application.

For this we are authorizing them more than once but we are getting refresh token once per user.

After  authorization we are fetching the customers under their account using getCustomers() method of customer service.
In first attempt to getCustomers() is working properly but when our clients authorize them second time we are getting the error "looks like your application is not properly configured with OAuth2 parameter refresh token is missing" 

In the getCustomers() request the access token is correct but we are not reciving the customers.

This method was working properly in the earlier version I was using v201802 but it is not working in the latest version v201809.

**Comment by AnashOommen** [comment]
Hi, 

Was this issue resolved? If not, could you drop an email to anash@google.com with a demo project that illustrates the issue?

**Comment by christopherseeley** [comment]
Closing this, feel free to reopen if this is ongoing,
