### ISSUE TITLE
Reporting API Calls - Feature Request

### ISSUE THREAD

**Issue by bbatton** [googleads/googleads-dotnet-lib#206]
In the future for the reporting functions in the API could there be an option to have the report returned as JSON instead of a gzipped file? This would reduce dependencies on a couple Microsoft libraries and would allow for faster calls back and forth to the API.

**Comment by AnashOommen** [comment]
Hi Brandon,

We can't provide this in the AdWords API, but we support this in Google Ads API (the next generation AdWords API). So if you move to https://github.com/googleads/google-ads-dotnet, you get back stats in native objects. Plus it uses protobuf + grpc, so the API call is much faster than either SOAP or JSON.

Tx
Anash

**Comment by AnashOommen** [comment]
Here's an example of the feature in action: https://github.com/googleads/google-ads-dotnet/blob/master/examples/Services/Reporting/GetKeywordStats.cs#L59
