### ISSUE TITLE
There is no AdWords.dll included

### ISSUE THREAD

**Issue by ArminLaidre** [googleads/googleads-dotnet-lib#207]
Hello,
I'm struck with updating from v201802 to v201809.
I'd prefer the binary distribution of the library by updating the dll's in my application's /bin folder. 
So I downloaded the files, but what confuses me is that there are no **Google.AdWords.dll** and Google.Ads.Common.dll files included in the /lib folder.
Shall I just keep the old versions, or... ?
What exactly are the files I need to update?
I appreciate your help.
Armin

**Comment by bbatton** [comment]
You have to pull the v201809 updates through nuget package manager. This will create all the needed files for you in your project along with all the related references. You can no longer update your project just using the repository source files.

**Comment by ArminLaidre** [comment]
OK, good to know. Thanks.

**Comment by christopherseeley** [comment]
bbatton is correct we now distribute through nuget
