### ISSUE TITLE
Oauth Token Generator Not working

### ISSUE THREAD

**Issue by br8kpoint** [googleads/googleads-dotnet-lib#209]
When running the latest version of the generator (the console version) the webpage opens and I click allow but then the localhost timesout with connection refused.

It takes a long time on the Confirm Your Choices screen. 

The console output then shows "An error occurred while authorizing the user."

How can I get the refresh token?

I have run the app also in admin console.

**Comment by christopherseeley** [comment]
Does this happen on multiple machines / networks? It's possible there's some firewall setting interfering.

**Comment by christopherseeley** [comment]
Closing this, feel free to reopen if this is still happening
