### ISSUE TITLE
SQL error when executing .exe

### ISSUE THREAD

**Issue by pollingerMaxi** [googleads/googleads-dotnet-lib#218]
Hello, i'm using version v201905 of the API.
Developing in C# VS 2017 Enterprise, using .net framework 4.7.1

When i execute the applicacion in the IDE (debugging) the program runs with no problems, it does what it has to do, no probs.
The problem comes when i execute the .exe file in the Debug/Release folder. I clean the solution, i build/rebuild the solution, generate the .exe again, and this is the error that i'm getting:
`Se produjo una excepción en el inicializador de tipo de "System.Data.SqlClient.SqlConnection"`

I attached my App.config (i extracted sensible data) for revision. Because i think the problem is in there, based on my google searches.

But i can't seem to find anything specific anywhere.

Any help will be appreciated.

Thanks in advance!

[github_config.txt](https://github.com/googleads/googleads-dotnet-lib/files/3422357/github_config.txt)

**Comment by pollingerMaxi** [comment]
Forgot to mention, using .net framework 4.7.1

**Comment by AnashOommen** [comment]
This is unrelated to the google admanager api libraries, since we don’t use SqlConnection. Could you post on StackOverflow please?

**Comment by pollingerMaxi** [comment]
> This is unrelated to the google admanager api libraries, since we don’t use SqlConnection. Could you post on StackOverflow please?

I don't think is unrelated since i have 2 applications that use the api and use the api config file. One works and the other doesn't.
I already searched on SO and other sites, and the problem seems to be in the config file. Since half my config file belongs to google's api configuration, i think it can be related to the api.

**Comment by AnashOommen** [comment]
One way to isolate this would be to remove all Google Ads API related keys from your App.config and try initializing GoogleAdManagerUser at runtime like this:

```c#
AdManagerAppConfig appConfig = new AdManagerAppConfig() {
  ....
};
AdManagerUser user = new AdManagerUser(appConfig);
```

**Comment by pollingerMaxi** [comment]
I finally was able to solve this.
The problem was that i had a duplicated `<add name="detailedRequestLogListener"` which was causing that error.

I uncommented that section because i was told by the web support to do that to enable de logging, but it caused that problem, sigh.

Thanks anyway for the help!
