### ISSUE TITLE
Video Campaigns

### ISSUE THREAD

**Issue by bbatton** [googleads/googleads-dotnet-lib#219]
AdWordsService.v201809.CampaignService

When using the get function on this service it won't return any video campaigns. It will return all other campaign types.

**Comment by bbatton** [comment]
Any update on this will be addressed?

**Comment by mkropachev** [comment]
Is there a solution to this problem?

**Comment by AnashOommen** [comment]
Nope, video campaigns are not supported in AdWords API, and I don't expect this to be fixed in the future.
