### ISSUE TITLE
TLS version issue

### ISSUE THREAD

**Issue by dev408** [googleads/googleads-dotnet-lib#222]
I have been running an application with version 201809 for several months with the .net libraries.  This Uses the Ad Hoc report from an AWQL query.  It's been working fine until last week.  Turns out our IT shop made a firewall change to block TLS1.0 and SSL v3 from traversing the firewall.  I can still run the same code with the same credentials when I am not on our corporate network but as soon as I connect to the network, the job fails.  Is there a way that I can code something to force the communication to be TLS 1.1 or greater.

I have attached the log file with the exceptions.

[Google Adwords API -- 10-15-19 14.41.37.675.log](https://github.com/googleads/googleads-dotnet-lib/files/3731125/Google.Adwords.API.--.10-15-19.14.41.37.675.log)

**Comment by christopherseeley** [comment]
AdWords API has been turned down and replaced with the Google Ads API. Closing as stale.
