### ISSUE TITLE
Update documentation: Required Admin rights

### ISSUE THREAD

**Issue by Gogims** [googleads/googleads-dotnet-lib#224]
I was not able to find anywhere in the [documentation](https://github.com/googleads/googleads-dotnet-lib/wiki/Using-OAuthTokenGenerator) that I needed to run the executable (OAuthTokenGenerator.exe) as an administrator. It took me a few hours to think about this scenario. I thought there was something wrong with my setup. 

Please update the [documentation](https://github.com/googleads/googleads-dotnet-lib/wiki/Using-OAuthTokenGenerator) to avoid other people going through the same as me.

**Comment by christopherseeley** [comment]
Updated documentation.
