### ISSUE TITLE
Can't create a bidding strategy with MaximizeConversions type 

### ISSUE THREAD

**Issue by smaralbashi** [googleads/googleads-dotnet-lib#227]
While it is possible from UI to create a portfolio strategy with MAXIMIZE_CONVERSIONS, the API does not allow and throws an error with INVALID_BIDDING_STRATEGY_TYPE. 

Is there any workwround for this ?

**Comment by christopherseeley** [comment]
AdWords API has been turned down and replaced with the Google Ads API. Closing as stale.
