### ISSUE TITLE
Inner exception blank while ManagedCustomerServiceError.UNKNOWN error

### ISSUE THREAD

**Issue by Swapygit** [googleads/googleads-dotnet-lib#229]
Hi Team,

We are using google adwords .Net library for implementing Mutate linking in our app. For that we are using ManagedCustomerService of the google adwords .Net library. We are getting the ManagedCustomerService.UNKNOWN exception in the code for some users. We are logging all the error messages in our api code. However, we required additional information regarding the ManagedCustomerServiceError.UNKNOWN error so we tried to log the stack trace and the inner exception. However, we did not get any additional information.

Can you help us to with what we can add in our code so that we could get the additional information about this error and then we can handle it our end and give some user friendly messages to the users.

**Comment by AnashOommen** [comment]
ManagedCustomerServiceError.UNKNOWN typically implies that there's some error code that is not yet exposed in the public API.  Pls drop an email to googleadsapi-support@google.com, and share with them the request / response logs, or the request ID / developer account customer ID if you can't get the logs. The team can lookup the actual error and share it over email.
