### ISSUE TITLE
Predicate Not Working

### ISSUE THREAD

**Issue by Gumdro** [googleads/googleads-dotnet-lib#230]
Ad Performance Report Predicate
API Version: v201809

The below predicate will result in ad performance metrics being returned that are not listed to be included in the predicate for reporting.

string[] adIds;
predicates = new Predicate[] { Predicate.In(Ad.Fields.Id, adIds) };

**Comment by christopherseeley** [comment]
AdWords API has been turned down and replaced with the Google Ads API. Closing as stale.
