### ISSUE TITLE
Geo Performance report returns zero based results

### ISSUE THREAD

**Issue by bobandrew** [googleads/googleads-dotnet-lib#231]
Hello,

I execute Geo Performance report and get 0 in CampaignName, CountryCriteriaId, RegionCriteriaId, CityCriteriaId columns. The header includeZeroImpressions is false. Below are my report results and code snippet
![image](https://user-images.githubusercontent.com/4517015/87760622-b0d8f400-c818-11ea-8ae9-4b91454ce930.png)
![image](https://user-images.githubusercontent.com/4517015/87760665-c1896a00-c818-11ea-81c7-a151ff069a17.png)

Could you help me realize why this happens?

**Comment by christopherseeley** [comment]
AdWords API has been turned down and replaced by the Google Ads API. Closing as stale.
