### ISSUE TITLE
AdWordsAppConfig Refresh Token is being lost

### ISSUE THREAD

**Issue by chowdud** [googleads/googleads-dotnet-lib#233]
I am using the AdWords library for the purpose of establishing a link between the customer and our MCC using the server side flow. The whole process works usually, but when swapping out the OAuth2 Credentials, it seems the flow loses the originally populated Refresh Token when "FetchAccessAndRefreshTokens" function gets executed. This leads to the subsequent CustomerService getCustomers function to fail as a result of this.

I'm not sure why this is occurring. Do you guys have any insights on this?

**Comment by christopherseeley** [comment]
AdWords API has been turned down and replaced with the Google Ads API. Closing as stale.
