### ISSUE TITLE
Google Adwords data freshness/ discrepancy issue

### ISSUE THREAD

**Issue by SagarMalbari** [googleads/googleads-dotnet-lib#234]
Hi Team,

We have some accounts under our MCC for which we fetch campaign performance LAST_14_DAYS report, using Google.Api.Ads.AdWords.v201809 API. We have been facing a data discrepancy issue from the past 2 days, which leads to incorrect data in our internal app reports.

Below is the ReportDefinition we are using for fetching the data,
ReportDefinition reportDefinition = new ReportDefinition
            {
                selector = selector,
                dateRangeType = ReportDefinitionDateRangeType.LAST_14_DAYS,
                downloadFormat = DownloadFormat.XML,
                reportName = "LAST_14_DAYS Performance",
                reportType = ReportDefinitionReportType.CAMPAIGN_PERFORMANCE_REPORT
            };
Could you please look into this and let us know the root cause of this issue, so that we can make changes at our side.

Thanks

**Comment by christopherseeley** [comment]
AdWords API has been turned down and replaced with the Google Ads API. Closing as stale.
