### ISSUE TITLE
OrderService.createOrders not setting startDateTime and endDateTime

### ISSUE THREAD

**Issue by In2Creation** [googleads/googleads-dotnet-lib#238]
Hi,

I am using this API for creating Orders in GAM.
When using the **createOrders** method of the **OrderService** the order gets created but startDateTime and endDateTime are always set to the current DateTime. Do I have to use another contract to update these values?

REQUEST ORDER:
order.startDateTime
{Google.Api.Ads.AdManager.v202011.DateTime}
    date: {Google.Api.Ads.AdManager.v202011.Date}
    hour: 0
    hourSpecified: true
    minute: 0
    minuteSpecified: true
    second: 0
    secondSpecified: true
    timeZoneId: "Europe/Brussels"
order.startDateTime.date
{Google.Api.Ads.AdManager.v202011.Date}
    day: 22
    daySpecified: true
    month: 6
    monthSpecified: true
    year: 2021
    yearSpecified: true

order.endDateTime
{Google.Api.Ads.AdManager.v202011.DateTime}
    date: {Google.Api.Ads.AdManager.v202011.Date}
    hour: 0
    hourSpecified: true
    minute: 0
    minuteSpecified: true
    second: 0
    secondSpecified: true
    timeZoneId: "Europe/Brussels"
order.endDateTime.date
{Google.Api.Ads.AdManager.v202011.Date}
    day: 30
    daySpecified: true
    month: 6
    monthSpecified: true
    year: 2021
    yearSpecified: true

RESPONSE ORDER:
createdOrders.FirstOrDefault().startDateTime
{Google.Api.Ads.AdManager.v202011.DateTime}
    date: {Google.Api.Ads.AdManager.v202011.Date}
    hour: 23
    hourSpecified: true
    minute: 0
    minuteSpecified: true
    second: 0
    secondSpecified: true
    timeZoneId: "Europe/Brussels"
createdOrders.FirstOrDefault().startDateTime.date
{Google.Api.Ads.AdManager.v202011.Date}
    day: 20
    daySpecified: true
    month: 6
    monthSpecified: true
    year: 2021
    yearSpecified: true
createdOrders.FirstOrDefault().endDateTime
{Google.Api.Ads.AdManager.v202011.DateTime}
    date: {Google.Api.Ads.AdManager.v202011.Date}
    hour: 23
    hourSpecified: true
    minute: 0
    minuteSpecified: true
    second: 0
    secondSpecified: true
    timeZoneId: "Europe/Brussels"
createdOrders.FirstOrDefault().endDateTime.date
{Google.Api.Ads.AdManager.v202011.Date}
    day: 20
    daySpecified: true
    month: 6
    monthSpecified: true
    year: 2022
    yearSpecified: true

Kind Regards,

Jan

**Comment by christopherseeley** [comment]
Hi Jan,

These are read only fields that are derived from the LineItems belonging to the Order:
https://developers.google.com/ad-manager/api/reference/v202105/OrderService.Order#startdatetime

**Comment by In2Creation** [comment]
Hi Christopher,

I was not aware of this, thanks for pointing this out.

Kind Regards,

Jan
