### ISSUE TITLE
Google Adwords API giving less data

### ISSUE THREAD

**Issue by habeebmatrix** [googleads/googleads-dotnet-lib#239]
I had been using Google Adwords Reports api (https://adwords.google.com/api/adwords/reportdownload/v201809) to fetch Data.
Since June 30th 2021, the API is returning only partial results. Because of this the Cost data is not being tracked properly at my end. Any idea of any updates regarding this in the reports API? Also this has affected only some of our accounts.

**Comment by christopherseeley** [comment]
Closing this since the AdWords API has been sunset.

**Comment by christopherseeley** [comment]
AdWords API has been turned down and replaced with the Google Ads API. Closing as stale.
