### ISSUE TITLE
	Could not load file or assembly 'Google.Apis.Core, Version=1.53.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' 

### ISSUE THREAD

**Issue by uidw7694** [googleads/googleads-dotnet-lib#240]
I have installed the latest nuget packages:

Install-Package Google.Cloud.PubSub.V1  -> 2.7.0
Install-Package Google.Cloud.Storage.V1 -> 3.60

When I’m trying the authentication example from  the documentation (see https://cloud.google.com/docs/authentication/getting-started#windows  ) I’m getting the following exception:
	Could not load file or assembly 'Google.Apis.Core, Version=1.53.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
	StackTrace    at Google.Cloud.Storage.V1.StorageClient.Create(GoogleCredential credential, EncryptionKey encryptionKey)

In app.config, I mapped the old version with the new version 

      <dependentAssembly>
        <assemblyIdentity name="Google.Apis.Core" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.53.0.0" newVersion="1.55.0.0" />
      </dependentAssembly>

Also I set the environment variable GOOGLE_APPLICATION_CREDENTIALS to the path of the JSON file that contains service account key.

Can please someone support me with this issue?

**Comment by christopherseeley** [comment]
This repo is for the Google Ad Manager API, not Cloud APIs.
