### ISSUE TITLE
forbidden error

### ISSUE THREAD

**Issue by eliebrahimi** [googleads/googleads-dotnet-lib#241]
I sent request via .NET  for API . the process of authentication is complete but I get error 403 (forbidden).
How can I resolve this issue?

Status(StatusCode="Unavailable", Detail="403:Forbidden", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1637654947.678000000","description":"Error received from peer ipv4:216.58.208.74:443","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\surface\call.cc","file_line":1062,"grpc_message":"403:Forbidden","grpc_status":14}")

**Comment by christopherseeley** [comment]
This library is for the Google Ad Manager API. The Google Ads library is available here:
https://github.com/googleads/google-ads-dotnet
