### ISSUE TITLE
[Urgent] FinalUrls is READONLY

### ISSUE THREAD

**Issue by ullfindsmit** [googleads/googleads-dotnet-lib#243]
In the latest library the FinalUrls property is READONLY
Assembly Google.Ads.GoogleAds, Version=10.2.0.0, Culture=neutral, PublicKeyToken=52807268f2b614dc

However, in the earlier version it was NOT readonly.
Assembly Google.Ads.GoogleAds, Version=10.1.0.0, Culture=neutral, PublicKeyToken=52807268f2b614dc

What is the new way to set the FinalURLs value?

**Comment by jradcliff** [comment]
Hi,

Based on the assembly and version you mentioned, you are not using this library for the AdWords API, but instead are using the library at https://github.com/googleads/google-ads-dotnet for the Google Ads API.

If so, could you open an issue at https://github.com/googleads/google-ads-dotnet/issues instead, and include more details such as the resource type where you are trying to set `FinalUrls`, and the error you are getting?

Thanks,
Josh, Google Ads API Team

**Comment by ullfindsmit** [comment]
Thank you for that info. I inherited this code, and this was the repo google sent me to.
I have created a ticket on the other repo that you can see here.
https://github.com/googleads/google-ads-dotnet/issues/337

**Comment by jradcliff** [comment]
Thanks. Let's continue the discussion on https://github.com/googleads/google-ads-dotnet/issues/337.
