### ISSUE TITLE
Upgrade from Nuget Package v11|Ads v10 to Nuget Package v15.0.1|The debugger does not proceed further past the service call.

### ISSUE THREAD

**Issue by Swapygit** [googleads/googleads-dotnet-lib#250]
Hi team,

We have .NET Web API 2.0 Project which is currently on .NET Framework version 4.7. We are consuming Google Ads API V10 for mutate link and reporting purposes. Recently we started to migrate to V13 of the Google Ads API. Also, we have migrated our web API project to .NET Framework 4.8 . When debugging the Google Ads API, we noticed that the debugger gets stuck at the step of performing service operations. 

Please find the code snippet below where the debugger is stuck.

      `   TraceUtilities.Configure(TraceUtilities.DETAILED_REQUEST_LOGS_SOURCE,
                    "E:\\Logs\\details.log", System.Diagnostics.SourceLevels.All);
      CustomerServiceClient customerService = googleAdsClient.GetService(Services.V13.CustomerService);
    string[] customerResourceNames = customerService.ListAccessibleCustomers();`

The debugger is stuck at ListAccessibleCustomers() method.

We even tried to add logging before the service call, however, only the log file is generated and no logs are written to the file.

All the dependencies of the NuGet packages are installed
appropriately.

Could you help us to resolve the same. Let us know if some more information is needed.

**Comment by christopherseeley** [comment]
This library is for the Ad Manager API. The Google Ads API library is available here:
https://github.com/googleads/google-ads-dotnet
