### ISSUE TITLE
Invalid timeout in `AdsSoapClient<TChannel>.Timeout`

### ISSUE THREAD

**Issue by dotjpg3141** [googleads/googleads-dotnet-lib#253]
Invalid timeout in `AdsSoapClient<TChannel>.Timeout`.

This should use [`TotalMilliseconds`](https://learn.microsoft.com/en-us/dotnet/api/system.timespan.totalmilliseconds?view=net-7.0) instead of [`Milliseconds`](https://learn.microsoft.com/en-us/dotnet/api/system.timespan.milliseconds?view=net-7.0).

https://github.com/googleads/googleads-dotnet-lib/blob/3c46029a71bf22dc0e6e785c5ef6b49db973efd9/src/Common/Lib/AdsSoapClient.cs#L34

**Comment by christopherseeley** [comment]
Fixed in [v24.25.0](https://github.com/googleads/googleads-dotnet-lib/releases/tag/v24.25.0)
