### ISSUE TITLE
Logging configuration - How to capture SOAP messages

### ISSUE THREAD

**Issue by ngaisteve1** [googleads/googleads-dotnet-lib#254]
From the wiki on [How to capture SOAP messages,](https://github.com/googleads/googleads-dotnet-lib/wiki/How-to-capture-SOAP-messages) it says `Logging can be enabled or disabled by editing the value attribute of the AdsClientLibs.SoapXmlLogs and AdsClientLibs.RequestInfoLog`

May I know where is `SoapXmlLogs` and `RequestInfoLogs`?

**Comment by christopherseeley** [comment]
These are set in the App.config file:
https://github.com/googleads/googleads-dotnet-lib/blob/main/examples/AdManager/CSharp/App.config#L111

Although the wiki looks out of date - it should be `AdsClientLibs.DetailedRequestLogs` and `AdsClientLibs.SummaryRequestLogs`. I just updated it to the correct values.
