### ISSUE TITLE
Strongly Typed Report Result

### ISSUE THREAD

**Issue by alperozcetin** [googleads/googleads-dotnet-lib#39]
Returning Strongly Typed Report Results. Or providing C# POCO classes to be serialized from XML results or any other way of consuming the service results with strongly typed classes.

**Comment by AnashOommen** [comment]
This should be fixed as of 20.0.0. See https://github.com/googleads/googleads-dotnet-lib/blob/master/ChangeLog#L32

We will update the wiki shortly (WIP). Meanwhile, see https://github.com/googleads/googleads-dotnet-lib/blob/master/examples/AdWords/CSharp/v201702/Reporting/StreamCriteriaReportToPoco.cs for an example.
