### ISSUE TITLE
multi threading with reportUtilities.GetResponse() - gets stuck

### ISSUE THREAD

**Issue by eratajczyk** [googleads/googleads-dotnet-lib#40]
Hi.
While multi threading report downloads this

           ReportResponse reportResponse = reportUtilities.GetResponse();
sometimes gets stuck.

There is no error message, or timeout or... anything.

I'm using 

           foreach(AdWordsUser user in adWordsUsers)
           {
                      foreach(ReportDefinition definition in definitions)
                      {
                                 Thread a = new Thread(new ThreadStart(delegate()
                                     { 
                      /*some code with GenerateRaport thing - it writes raport data to a database*/
                                     }));
                      }
             }

           public StringBuilder GenerateRaport(AdWordsUser awUser, ReportDefinition reportDefinition)
                   {
                       StringBuilder reportText = new StringBuilder();
                       ReportUtilities reportUtilities = new ReportUtilities(awUser, "v201409", reportDefinition);
                       try
                       {
                               ReportResponse reportResponse = reportUtilities.GetResponse();
                               byte[] reportBytes = reportResponse.Download();
                               reportText.Append(Encoding.UTF8.GetString(reportBytes));
                       }
                       catch (Exception ex)
                       {
                           errorLog.WriteLine(System.DateTime.Now.ToString() + ": " + (awUser.Config as      AdWordsAppConfig).ClientCustomerId.ToString() + " " + reportDefinition.reportName);
                           errorLog.WriteLine(ex.ToString());
                           reportText.Append("");
                           errorLog.Flush();
                       }
                       return reportText;
                      }

It have never stucked with no threading.
How to multithread this safe?

**Comment by jimper** [comment]
Hi there,

ReportResponse is a disposable object, which wraps an underlying WebRequest and WebResponse. Unless it is disposed of by manually calling ``Dispose()`` or wrapping the code in a ``using`` statement, .NET will eventually stop opening connections.

There are examples of how to handle these objects properly in our [reporting migration guide](https://github.com/googleads/googleads-dotnet-lib/wiki/Migrating-to-the-new-version-of-ReportUtilities).

**Comment by eratajczyk** [comment]
Thank you for your comment (i've had wrapped that before, it was the same :()
Will check again.
