### ISSUE TITLE
Whither ApiErrorType?

### ISSUE THREAD

**Issue by gmti-ggreer** [googleads/googleads-dotnet-lib#43]
You may have been a bit too aggressive removing the ".Type" fields for DFP API v201502 because the client library's "ApiError.ApiErrorType" field is gone too. (I have C# client library 18.10.0.0)

I thought perhaps the comment about typeof/instanceof/etc. in the DFP API release notes meant the method had changed so I went looking for a different field and serialized an ApiException to:
```json
{
   "message" : "[TeamError.ALL_TEAM_ASSOCIATION_NOT_ALLOWED @ appliedTeamIds; trigger:'28469']",
   "errors" : [
      {
         "fieldPath" : "appliedTeamIds",
         "reason" : 4,
         "trigger" : "28469",
         "reasonSpecified" : true,
         "errorString" : "TeamError.ALL_TEAM_ASSOCIATION_NOT_ALLOWED"
      }
   ]
}
```
but other than substring'ing "errorString" I don't see a reasonable replacement for what "errors[x].ApiErrorType" used to have.  (As an aside, the client library doesn't recognize the existence of the "reason" field above, if that is supposed to be included.)

Alternatively, you forgot to update your "Getting Started" guide https://github.com/googleads/googleads-dotnet-lib/wiki/Getting-Started regarding error handling and I missed whatever notification was put out regarding a change in exception handling, which wouldn't surprise me given how busy I've been.

While talking about the "Getting Started" guide's example, there is no "ErrorUtilities" in the DFP C# client library.

For reference, the error handling I use looks like:
```csharp
                catch (DfpApiException e) {
                    ApiException eapi = (ApiException)e.ApiException;
                    foreach (ApiError err in eapi.errors) {
                        if (err.ApiErrorType == "QuotaError") {
                            QuotaError qerr = (QuotaError)err;
                            if (qerr.reason == QuotaErrorReason.EXCEEDED_QUOTA) {
                                Console.WriteLine("\tExceeded quota.");
                                Thread.Sleep(1000 * 1); // 1 second
                                goto re/*try*/;
                            }
                        } else if (err.ApiErrorType == "FeatureError") {
...etc...
```
(I don't particularly like comparing them as strings but such is life.)

**Comment by Narwalter** [comment]
ApiError is an abstract class with classes like FeatureError and QuotaError extending it, so you can use the class to determine the error type. 

Your latter guess is right - we didn't update the Getting Started guide. I've done so now to reflect the DFP changes:
https://github.com/googleads/googleads-dotnet-lib/wiki/Getting-Started#dfp-api
