### ISSUE TITLE
ReportResponse Text and Contents Missing

### ISSUE THREAD

**Issue by addamsviz** [googleads/googleads-dotnet-lib#50]
The ReportResponse.Text and Contents methods are missing in the Ads API .NET Client Library - v18.14.0.  I have tried accessing these methods through our custom application and adding them to the AdWords.Examples project but they are not available and give the below compile error message:
'Text' is not a member of 'Google.Api.Ads.Common.Util.Reports.ReportResponse'.	

The documentation here for Downloading Reports indicates that these methods are still available:
https://github.com/googleads/googleads-dotnet-lib/wiki/Downloading-Reports

I changed our code to use the ReportResponse.stream to work around the issue.

Thank you.

**Comment by AnashOommen** [comment]
I cleaned up the wiki to reflect these changes.
