### ISSUE TITLE
Keyword Performance Report FinalUrls not returning URL for mobile

### ISSUE THREAD

**Issue by addamsviz** [googleads/googleads-dotnet-lib#52]
We are using the Reporting API to download the Keyword Performance Report and it appears that only the main Final URL is always returned even if a URL for mobile is defined and there are impressions/clicks for mobile devices.  In the report documentation it says that the FinalUrls field returns a "List of final URLs of the main object of this row.", but the .NET library always returns a string attribute for finalURL for each row.  Should the finalURL attribute return the URL for mobile that was clicked if it is a mobile device type?

**Comment by jradcliff** [comment]
To retrieve the final mobile URLs, please use the [finalMobileUrls field](https://developers.google.com/adwords/api/docs/appendix/reports/keywords-performance-report#finalmobileurls).
