### ISSUE TITLE
Error on .NET BatchJobUtilities instance creation

### ISSUE THREAD

**Issue by rr1801** [googleads/googleads-dotnet-lib#59]
I'm having troubles creating a BatchJobUtilities instance. I followed the code on .NET examples (https://github.com/googleads/googleads-dotnet-lib/blob/master/examples/AdWords/CSharp/v201509/CampaignManagement/AddCompleteCampaignsUsingBatchJob.cs), but when i call 
BatchJobUtilities batchJobUploadHelper = new BatchJobUtilities(user)
I get a StackOverflowException (the AdWordsUser user object is already instantiated and working - i used it on reporting before).

Thank you,
Rafael

**Comment by AnashOommen** [comment]
Fixed in v18.20.0.

**Comment by SaritaA** [comment]
v18.20.0. It's new version.

**Comment by SaritaA** [comment]
I'm having troubles creating a BatchJobUtilities instance. I followed the code on .NET examples (https://github.com/googleads/googleads-dotnet-lib/blob/master/examples/AdWords/CSharp/v201509/CampaignManagement/AddCompleteCampaignsUsingBatchJob.vb), but when i call 
BatchJobUtilities batchJobUploadHelper = new BatchJobUtilities(user)
I get a StackOverflowException

**Comment by AnashOommen** [comment]
Hi,

This is fixed in the latest version of the client library, could you try
using it?

Thx
Anash
