### ISSUE TITLE
ReportUtilities hangs after consequitve calls 

### ISSUE THREAD

**Issue by denizerkan2** [googleads/googleads-dotnet-lib#69]
Hi, 
I saw another issue regarding this but the problem is still there for long running server scenarios. I'm pasting the code below, where the server is trying to download a report from AdWords in an infinite loop.  The below code is executed multiple times in a larger loop, it traverses all accounts, all campaigns, etc...It works, until eventually it hangs. No exceptions thrown. When I break into the code in Visual Studio, it's waiting for the below line to execute. 

using (Google.Api.Ads.Common.Util.Reports.ReportResponse response = utilities.GetResponse())

Note that while it's undeterministic when it'll finally hang, but eventually it does, after around maybe 30-40 loops. 
Any idea what's happening here?

            int downloadAttempts = 1;
            while (true)
            {
                try
                {

                    ReportUtilities utilities = new ReportUtilities(user, "v201506", definition);
                    using (Google.Api.Ads.Common.Util.Reports.ReportResponse response = utilities.GetResponse())
                    {
                        response.Save(saveFileName);
                        retval = new FileStream(saveFileName,FileMode.Open);
                    }
                    break;

                }
                catch (Exception ex)
                {
                    string errMessage = ex.Message;
                    if (ex.InnerException != null)
                        errMessage = errMessage + ex.InnerException.Message;
                    Console.WriteLine("Attempt:{0}. Failed to download report.{1}", downloadAttempts, errMessage);
                    downloadAttempts++;
                    // return retval;
                    //                    throw new System.ApplicationException("Failed to download report.", ex);
                }
            }

**Comment by AnashOommen** [comment]
Is this a webserver by any chance? Or is this code multi threaded? If yes, you'd want to increase the maximum number of simultaneous connections on your server. You can either do
```
System.Net.ServicePointManager.DefaultConnectionLimit = 100;
```
or in your <code>Web.config</code>, add

```
<configuration>
  <system.net>
    <connectionManagement>
      <add address = "*" maxconnection = "100" />
    </connectionManagement>
  </system.net>
</configuration>
```

If it isn't, feel free to reopen this issue and attach a small code snippet that replicates the issue.

**Comment by denizerkan2** [comment]
Thanks for the tip. It is a server side code, and it creates multiple threads depending on the load, so yes and yes. I'll do this modification and will re-open if I see the issue recurring.

Thx!
