### ISSUE TITLE
AdWords Dependency on machine.config and writing files to the local drive

### ISSUE THREAD

**Issue by rjmccammon** [googleads/googleads-dotnet-lib#70]
Part 1:
I need the dependency of the following lines requirement to be added to machine/web/app.config to be removed:

      <soapExtensionTypes>
        <add type="Google.Api.Ads.Common.Lib.SoapListenerExtension, Google.Ads.Common"
              priority="1" group="0"/>
      </soapExtensionTypes>

To avoid the error "{"The SoapListenerExtension class is not loaded. The most possible cause for this error is that you haven't registered 
Google.Api.Ads.Common.Lib.SoapListenerExtension as a soap extension under 
configuration/system.web/webServices/soapExtensionTypes in your your App.config or Web.config. See the sample 
App.config for details on how to register soap extensions."}".

Part 2:
Need to be able to turn off diagnostic logging to the server drive.

**Comment by AnashOommen** [comment]
I'll release a new version with the requested features later this week (or early next week).

**Comment by rjmccammon** [comment]
@AnashOommen Was this completed?

**Comment by rjmccammon** [comment]
@AnashOommen 
I'm still getting the following error with the new code and I set the EnableSoapExtension to false.

{"The SoapListenerExtension class is not loaded. The most possible cause for this error is that you haven't registered Google.Api.Ads.Common.Lib.SoapListenerExtension as a soap extension under configuration/system.web/webServices/soapExtensionTypes in your your App.config or Web.config. See the sample App.config for details on how to register soap extensions."}

**Comment by AnashOommen** [comment]
This fix is live as of v18.23.0.
