### ISSUE TITLE
v18.23.0 finalurl and mobileFinalURL issue

### ISSUE THREAD

**Issue by addamsviz** [googleads/googleads-dotnet-lib#77]
We recently upgraded to v18.23.0 and API v201601 and noticed a change in the format of the finalurl and mobileFinalURL fields that we pull using the KEYWORDS_PERFORMANCE_REPORT through the reporting API.  The data returned in these fields is now always surrounded by [""].  For example: ["http://www.example.com"]

The URLs that have been returned in these fields in previous versions of the API have never been surrounded by these characters and it caused some problems for our import.  It seems like these characters should not be returned and that this may be in error.  For the time being we are just going to remove the characters in our code but it seems like this should be corrected.  Thank you.

**Comment by jradcliff** [comment]
Hi,

Am I correct in assuming you upgraded from v201506? The reason I ask is that in v201509, we changed several fields to return JSON lists or maps. Please see the **Miscellaneous reporting changes** section of the v201509 migration guide:

https://developers.google.com/adwords/api/docs/reference/#misc-reporting

Thanks,
Josh, AdWords API Team

**Comment by addamsviz** [comment]
Hi Josh,

Thank you for the quick response.  Yes, you are correct that we upgraded from v201506.  I will update our code to parse the JSON list returned in the finalurl and mobileFinalURL fields.  What would he use case be for having multiple final urls as I do not believe this applies to my organization?  Thank you.

**Comment by jradcliff** [comment]
Hi,

One example would be if you are using a tracking template that redirects a portion of your traffic to final URL A and the rest to final URL B. Our [Upgraded URLs guide](https://developers.google.com/adwords/api/docs/guides/upgraded-urls) covers this in more detail.

I'll close this issue, but feel free to reach out via the forum if you have additional questions about final URLs.

https://groups.google.com/forum/#!forum/adwords-api

Thanks,
Josh, AdWords API Team
