### ISSUE TITLE
Invalid file dates inside Nuget packages

### ISSUE THREAD

**Issue by dstarosta** [googleads/googleads-dotnet-lib#88]
This issue is happening with both, Google.Dfp and the dependent Google.Ads.Common, packages. It looks like the created and modified dates on the DLL files are not set correctly inside the packages (see the screenshot below).

Our Jenkins build server sets the file dates to 1/1/1980 12:00:00 AM. It remains the same if we update the Nuget package to the newer version which causes ASP .NET to still work with the old (cached) library version (because the file date has not changed). The only way to fix the DLL binding error is to stop IIS and clear the ASP .NET Temporary Files folder, or manually overwrite the DLL files on the server which is not an option in production.

![dll_time](https://cloud.githubusercontent.com/assets/1761905/16098738/97627878-3322-11e6-99d9-7fcc7cc6855e.jpg)

**Comment by christopherseeley** [comment]
This looks like a bug when packing under linux:
https://github.com/NuGet/Home/issues/624

We probably need to update our nuget version

**Comment by AnashOommen** [comment]
Fixed in the latest release.
