### ISSUE TITLE
The remote server returned an error: (404) Not Found

### ISSUE THREAD

**Issue by zpbd** [googleads/googleads-dotnet-lib#91]
Hi. I've upgraded the package via nuget since Google deprecated the API version we were on. We are now using Google.Ads.Common version="3.15.1" with Google.AdWords version="18.28.0".

Before we were on 3.11.0 and 18.21.0 respectively, using v201509

The stacktrace is as follows:
```
AdWordsReportsException: One or more AdWords Report download errors have occurred.
"The remote server returned an error: (404) Not Found."
at Google.Api.Ads.AdWords.Util.Reports.ReportUtilities.DownloadReport(String downloadUrl, String postBody)
   at Google.Api.Ads.AdWords.Util.Reports.ReportUtilities.GetReport()
   at Google.Api.Ads.Common.Util.Reports.AdsReportUtilities.GetResponse()
   at Google.Api.Ads.AdWords.Util.Reports.ReportUtilities.GetResponse()
```

I've regenerate the refresh token and tried various config changes, but we still get the 404.

**Comment by AnashOommen** [comment]
AdWords API v201509 has been sunset. Could you please switch to the latest version? That should bring you upto v201605, which is currently the latest API version. Migration guides are [here](https://developers.google.com/adwords/api/docs/guides/migration/v201603).

**Comment by zpbd** [comment]
Hi Anash, sorry I wasn't clear enough. *Before* we were on v201509, I was just trying to give context. But this error is occuring on v201605.
