### ISSUE TITLE
Potential XXE in /src/Common/Util/SerializationUtilities.cs

### ISSUE THREAD

**Issue by highjack** [googleads/googleads-dotnet-lib#95]
Hi,
I believe there is a potential External Xml Entities issue in the following file at line 51: /src/Common/Util/SerializationUtilities.cs

xDoc.LoadXML(xmlText); is called without first setting the XmlResolver to null, I tried this section of code locally in a test app and I was able to use this to send requests to web server by setting  "xmlText" to the following:
<?xml version="1.0" ?>
<!DOCTYPE r [
<!ELEMENT r ANY >
<!ENTITY sp SYSTEM "http://127.0.0.1:8000/test.txt">
]>
<r>&sp;</r>

I started a local web server using python -m SimpleHTTPServer to monitor the requests, doing so I can see the GET requests from the .NET app to the web server.

From what I can tell xmlText can come from the response to a soap request so if there is any way of an attacker modifying this content, they can read text files and XML files from the boxes this code is deployed on.

Thanks

**Comment by AnashOommen** [comment]
Hi,

Thanks for reporting this issue, I'll take a look today.

**Comment by christopherseeley** [comment]
Fixed in the latest release
