### ISSUE TITLE
Consider support for .Net Core

### ISSUE THREAD

**Issue by SaanichGAS** [googleads/googleads-dotnet-lib#96]
Given the push to .Net Core for many C# applications and services, it would be helpful to have a client library that supports this; in particular for cases where platforms such as AWS Lambda are being considered (which requires .Net Core for C# implementation).

**Comment by AnashOommen** [comment]
We have work in progress towards this goal. Two of the major pieces are being worked on right now (Moving to WCF and bumping the runtime requirement to 4.5.2). Once those go live, we will run the .NET Portability Analyzer to analyze and fix additional dependencies (there shouldn't be too much of them).

**Comment by dwdickens** [comment]
+1. Looking forward to this!

**Comment by edblackburn** [comment]
Hi @AnashOommen may I enquire as to how this is progressing? Do you have insight into lead times? Are we weeks or months away, is there much priority attributed to `dotnetcore` currently? Many thanks, Ed

**Comment by rfrancisco** [comment]
Any news regarding this? We are currently migrating a solution, and that migration was planned couple of months ago expecting to have the dfp api available. We know that things get delayed, and that's fine, but could you provide us with an ideia of the progress that has been made towards this goal, and if possible an ideia of when this could become available?

Thanks in advance

**Comment by christopherseeley** [comment]
We're working to upgrade our SOAP toolkit, which is the major blocker. Do you have a particular version of Core that you need? Also, to confirm you're looking to use the DFP SOAP trafficking API correct? This client library doesn't handle ad serving.

**Comment by rfrancisco** [comment]
Yes, we use this API to do many things, some of witch are: query DFP inventory, write custom attributes in orders, orderlines, etc, update creative wrappers, etc...

**Comment by christopherseeley** [comment]
As an update here, v21.0.0 updated the SOAP toolkit which was the major blocker. We're looking into .NET Standard 2.0 support which would bring .NET Core 2.0 support.

**Comment by rfrancisco** [comment]
Is this something you are planning to do for the next release?

**Comment by 4nonym0us** [comment]
+1. Would be great to have .NET Core support.

**Comment by thaDude** [comment]
Hello, any news on this? Thanks.

**Comment by rfrancisco** [comment]
Hi guys. Its been almost 4 months since @christopherseeley mentioned that the SOAP toolkit had been migrated and that you were looking into .Net Standard 2 support.
Could you give us an update on this? And if possible a possible timetable for .Net core support

**Comment by christopherseeley** [comment]
We're working through replacing other dependencies that aren't .NET Standard compatible. There's no hard timetable at the moment but it's something we're actively working on, and a high priority.

**Comment by rfrancisco** [comment]
Could you provide a rough estimate?

**Comment by christopherseeley** [comment]
I opened #125, #126, and #127 which are the remaining blockers. The library can add .NET Standard 2.0 support after these are resolved.

**Comment by AnashOommen** [comment]
I also opened #128 as yet another blocker.

**Comment by goncalolucas** [comment]
Hi, any news on this? Any estimate date? Thanks.

**Comment by christopherseeley** [comment]
We're planning on a release with .NET Standard 2.0 support by end of this quarter.

**Comment by christopherseeley** [comment]
Added support for .NET Standard in v23.0.0.
Note that there are some .NET Core specific issues that impact our library. See issue #133 and issue #134 for details.
